export type Sentence = [string, string];

export interface Category {
  id: string;
  label: string;
  title: string;
  pattern: string;
  rule: string;
  sentences: Sentence[];
}

export const categories: Category[] = [
  {
    id: "presente",
    label: "Presente rotina",
    title: "Presente — rotina e hábitos",
    pattern: "I [verb] as/at/in...",
    rule: "Usado para falar de rotina, profissão e hábitos. O verbo é simples, sem -ing.",
    sentences: [
      ["I work as a product designer.", "Eu trabalho como product designer."],
      ["I live in Brazil.", "Eu moro no Brasil."],
      ["I design digital products every day.", "Eu projeto produtos digitais todo dia."],
      ["I work at a tech company.", "Eu trabalho em uma empresa de tecnologia."],
      ["I collaborate with developers and stakeholders.", "Eu colaboro com desenvolvedores e stakeholders."],
      ["I use Figma to create prototypes.", "Eu uso Figma para criar protótipos."],
      ["I lead design projects from start to finish.", "Eu lidero projetos de design do início ao fim."],
      ["I speak Portuguese and some English.", "Eu falo português e um pouco de inglês."],
      ["I study English every week.", "Eu estudo inglês toda semana."],
      ["I work remotely most of the time.", "Eu trabalho remotamente na maior parte do tempo."],
    ],
  },
  {
    id: "presente_agora",
    label: "Presente agora",
    title: "Presente — o que está acontecendo agora",
    pattern: "I am [verb]-ing...",
    rule: "Usado para falar do que está acontecendo nesse momento. Sempre usa am/is/are + verbo-ing.",
    sentences: [
      ["I am working on a new project.", "Eu estou trabalhando em um projeto novo."],
      ["I am learning English right now.", "Eu estou aprendendo inglês agora."],
      ["I am building a design system.", "Eu estou construindo um design system."],
      ["I am talking to a client.", "Eu estou falando com um cliente."],
      ["I am improving my skills.", "Eu estou melhorando minhas habilidades."],
      ["I am living in Sumaré.", "Eu estou morando em Sumaré."],
      ["I am working on a presentation.", "Eu estou trabalhando em uma apresentação."],
      ["I am reading about UX research.", "Eu estou lendo sobre UX research."],
      ["I am looking for new opportunities.", "Eu estou procurando novas oportunidades."],
      ["I am growing as a professional.", "Eu estou crescendo como profissional."],
    ],
  },
  {
    id: "passado",
    label: "Passado simples",
    title: "Passado — o que já aconteceu",
    pattern: "I [verb-ed / irregular] at/in/for...",
    rule: "Verbos regulares recebem -ed. Irregulares mudam a forma inteira. Usado para falar de eventos concluídos.",
    sentences: [
      ["I worked at a startup for 3 years.", "Eu trabalhei em uma startup por 3 anos."],
      ["I designed the entire app from scratch.", "Eu projetei o app inteiro do zero."],
      ["I lived in São Paulo for a while.", "Eu morei em São Paulo por um tempo."],
      ["I led a team of five people.", "Eu liderei uma equipe de cinco pessoas."],
      ["I built a design system for the company.", "Eu construí um design system para a empresa."],
      ["I finished the project on time.", "Eu terminei o projeto no prazo."],
      ["I worked with international clients.", "Eu trabalhei com clientes internacionais."],
      ["I started my career as a junior designer.", "Eu comecei minha carreira como designer junior."],
      ["I moved to Sumaré two years ago.", "Eu me mudei para Sumaré há dois anos."],
      ["I gave up that job because it was toxic.", "Eu desisti daquele emprego porque era tóxico."],
    ],
  },
  {
    id: "passado_neg",
    label: "Passado negativo",
    title: "Passado — negativa com didn't",
    pattern: "I didn't [verbo normal]...",
    rule: "Depois de didn't o verbo sempre volta ao normal, sem -ed. Mesma regra para todas as pessoas.",
    sentences: [
      ["I didn't finish the project on time.", "Eu não terminei o projeto no prazo."],
      ["I didn't work as a developer.", "Eu não trabalhei como desenvolvedor."],
      ["I didn't leave because of money.", "Eu não saí por causa de dinheiro."],
      ["I didn't know how to code before.", "Eu não sabia programar antes."],
      ["I didn't speak English at that time.", "Eu não falava inglês naquela época."],
      ["I didn't like that project.", "Eu não gostei daquele projeto."],
      ["I didn't have a team to help me.", "Eu não tinha equipe para me ajudar."],
      ["I didn't expect that result.", "Eu não esperava aquele resultado."],
      ["I didn't give up even when it was hard.", "Eu não desisti mesmo quando foi difícil."],
      ["I didn't see that problem coming.", "Eu não vi aquele problema vindo."],
    ],
  },
  {
    id: "futuro_will",
    label: "Futuro — will",
    title: "Futuro — decisão na hora ou promessa",
    pattern: "I will [verbo direto]...",
    rule: "Will não usa 'to' depois. Vai direto pro verbo. Usado para decisões tomadas agora ou promessas.",
    sentences: [
      ["I will send you the file tomorrow.", "Eu vou te mandar o arquivo amanhã."],
      ["I will finish the project this week.", "Eu vou terminar o projeto essa semana."],
      ["I will improve my English this year.", "Eu vou melhorar meu inglês esse ano."],
      ["I will call you later.", "Eu vou te ligar mais tarde."],
      ["I will help you with the design.", "Eu vou te ajudar com o design."],
      ["I will learn new tools next month.", "Eu vou aprender novas ferramentas no próximo mês."],
      ["I will lead the next project.", "Eu vou liderar o próximo projeto."],
      ["I will share the presentation today.", "Eu vou compartilhar a apresentação hoje."],
      ["I will not give up on this.", "Eu não vou desistir disso."],
      ["I will start studying tomorrow.", "Eu vou começar a estudar amanhã."],
    ],
  },
  {
    id: "futuro_going",
    label: "Futuro — going to",
    title: "Futuro — plano já decidido",
    pattern: "I am going to [verbo]...",
    rule: "Usado para planos que já foram decididos antes. Diferente do will, que é decisão na hora.",
    sentences: [
      ["I am going to start a new project next week.", "Eu vou começar um projeto novo semana que vem."],
      ["I am going to travel to Europe next year.", "Eu vou viajar para a Europa ano que vem."],
      ["I am going to present my work to the team.", "Eu vou apresentar meu trabalho para o time."],
      ["I am going to learn UX writing.", "Eu vou aprender UX writing."],
      ["I am going to change jobs this year.", "Eu vou mudar de emprego esse ano."],
      ["I am going to build my portfolio.", "Eu vou construir meu portfólio."],
      ["I am going to take an English course.", "Eu vou fazer um curso de inglês."],
      ["I am going to work from home next week.", "Eu vou trabalhar de casa semana que vem."],
      ["I am going to talk to my manager tomorrow.", "Eu vou falar com meu gestor amanhã."],
      ["I am going to move to a bigger city.", "Eu vou me mudar para uma cidade maior."],
    ],
  },
  {
    id: "do_does",
    label: "Do / Does",
    title: "Do / Does — perguntas e negativas no presente",
    pattern: "Do/Does + sujeito + verbo?",
    rule: "Do → I, You, We, They. Does → He, She, It. Com does/doesn't o verbo fica no normal, sem -s no final.",
    sentences: [
      ["Do you work remotely?", "Você trabalha remotamente?"],
      ["Does she have experience in UX?", "Ela tem experiência em UX?"],
      ["Do they use Figma?", "Eles usam Figma?"],
      ["Does he speak English?", "Ele fala inglês?"],
      ["Do you have a portfolio?", "Você tem um portfólio?"],
      ["I don't work on weekends.", "Eu não trabalho nos fins de semana."],
      ["She doesn't like that design.", "Ela não gosta daquele design."],
      ["They don't use that tool.", "Eles não usam aquela ferramenta."],
      ["He doesn't have a LinkedIn.", "Ele não tem LinkedIn."],
      ["We don't work with that client anymore.", "Nós não trabalhamos mais com aquele cliente."],
    ],
  },
  {
    id: "did",
    label: "Did / Didn't",
    title: "Did / Didn't — perguntas e negativas no passado",
    pattern: "Did + sujeito + verbo? / I didn't + verbo",
    rule: "Did é igual para todo mundo no passado. Depois de did/didn't o verbo sempre volta ao normal.",
    sentences: [
      ["Did you work on that project?", "Você trabalhou naquele projeto?"],
      ["Did she finish the design on time?", "Ela terminou o design no prazo?"],
      ["Did they approve the proposal?", "Eles aprovaram a proposta?"],
      ["Did he leave the company?", "Ele saiu da empresa?"],
      ["Did you have a good experience there?", "Você teve uma boa experiência lá?"],
      ["I didn't finish the project on time.", "Eu não terminei o projeto no prazo."],
      ["She didn't like the feedback.", "Ela não gostou do feedback."],
      ["They didn't approve the design.", "Eles não aprovaram o design."],
      ["He didn't show up to the meeting.", "Ele não apareceu para a reunião."],
      ["We didn't have enough time.", "Nós não tínhamos tempo suficiente."],
    ],
  },
  {
    id: "have_has",
    label: "Have / Has",
    title: "Have / Has — ter e experiência",
    pattern: "I have / She has + [substantivo ou verbo no passado]",
    rule: "Have → I, You, We, They. Has → He, She, It. Como experiência: I have worked here for 8 years.",
    sentences: [
      ["I have 8 years of experience.", "Eu tenho 8 anos de experiência."],
      ["She has a strong portfolio.", "Ela tem um portfólio forte."],
      ["We have a meeting at 3pm.", "Nós temos uma reunião às 15h."],
      ["He has a lot of experience in UX.", "Ele tem muita experiência em UX."],
      ["They have a new client.", "Eles têm um novo cliente."],
      ["I have worked here for 2 years.", "Eu trabalho aqui há 2 anos."],
      ["She has already finished the project.", "Ela já terminou o projeto."],
      ["We have never missed a deadline.", "Nós nunca perdemos um prazo."],
      ["He has built three design systems.", "Ele já construiu três design systems."],
      ["They have grown a lot this year.", "Eles cresceram muito esse ano."],
    ],
  },
  {
    id: "was_were",
    label: "Was / Were",
    title: "Was / Were — passado do ser e estar",
    pattern: "I/He/She was — You/We/They were",
    rule: "Was → I, He, She, It. Were → You, We, They. Negativa: wasn't / weren't.",
    sentences: [
      ["I was a junior designer 5 years ago.", "Eu era designer junior há 5 anos."],
      ["She was the lead on that project.", "Ela era a líder naquele projeto."],
      ["We were a team of 4 people.", "Nós éramos uma equipe de 4 pessoas."],
      ["It was a very complex project.", "Era um projeto muito complexo."],
      ["They were great clients.", "Eles eram ótimos clientes."],
      ["I wasn't happy at that job.", "Eu não estava feliz naquele emprego."],
      ["She wasn't ready for that role.", "Ela não estava pronta para aquela função."],
      ["We weren't aligned on the deadline.", "Nós não estávamos alinhados sobre o prazo."],
      ["Was the meeting productive?", "A reunião foi produtiva?"],
      ["Were you the designer on that project?", "Você era o designer naquele projeto?"],
    ],
  },
  {
    id: "auxiliares",
    label: "Can / Could",
    title: "Can / Could — conseguir e pedir com educação",
    pattern: "Can = consigo | Could = poderia (mais educado)",
    rule: "Depois de can/could o verbo é sempre normal, sem -ing ou -ed. Could é mais educado que can.",
    sentences: [
      ["I can work under pressure.", "Eu consigo trabalhar sob pressão."],
      ["I can't speak English fluently yet.", "Eu ainda não consigo falar inglês fluentemente."],
      ["Can you review my design?", "Você pode revisar meu design?"],
      ["She can lead a team of 10 people.", "Ela consegue liderar uma equipe de 10 pessoas."],
      ["Could you send me the brief?", "Você poderia me mandar o briefing?"],
      ["Could we reschedule the meeting?", "Poderíamos remarcar a reunião?"],
      ["I could work on that tomorrow.", "Eu poderia trabalhar nisso amanhã."],
      ["Can we jump on a call later?", "Podemos fazer uma call mais tarde?"],
      ["I can deliver this by Friday.", "Eu consigo entregar isso até sexta."],
      ["Could you explain that again?", "Você poderia explicar isso de novo?"],
    ],
  },
  {
    id: "should_must",
    label: "Should / Must",
    title: "Should / Must — conselho e obrigação",
    pattern: "Should = deveria | Must = precisa/obrigado",
    rule: "Should → conselho. Must → obrigação forte. Ambos seguidos de verbo normal, sem to.",
    sentences: [
      ["You should improve your English.", "Você deveria melhorar seu inglês."],
      ["I should update my portfolio.", "Eu deveria atualizar meu portfólio."],
      ["She should ask for feedback.", "Ela deveria pedir feedback."],
      ["You shouldn't give up so easily.", "Você não deveria desistir tão fácil."],
      ["I must finish this by Friday.", "Eu preciso terminar isso até sexta."],
      ["We must meet the deadline.", "Nós precisamos cumprir o prazo."],
      ["You must not share this file.", "Você não pode compartilhar esse arquivo."],
      ["I should learn more about accessibility.", "Eu deveria aprender mais sobre acessibilidade."],
      ["Should I send the file now?", "Eu deveria mandar o arquivo agora?"],
      ["He must improve his communication skills.", "Ele precisa melhorar suas habilidades de comunicação."],
    ],
  },
  {
    id: "wh",
    label: "WH Questions",
    title: "WH Questions — perguntas abertas",
    pattern: "[WH] + do/did/will + sujeito + verbo?",
    rule: "What, Where, When, Who, Why, How. No passado usa did. No presente usa do/does. Com auxiliares inverte a ordem.",
    sentences: [
      ["What do you do for a living?", "O que você faz para viver?"],
      ["Where do you work?", "Onde você trabalha?"],
      ["When did you start your career?", "Quando você começou sua carreira?"],
      ["Why did you leave your last job?", "Por que você saiu do último emprego?"],
      ["How do you manage your projects?", "Como você gerencia seus projetos?"],
      ["Who did you work with on that project?", "Com quem você trabalhou naquele projeto?"],
      ["What will you do next year?", "O que você vai fazer no ano que vem?"],
      ["Where did you learn design?", "Onde você aprendeu design?"],
      ["How long did you work there?", "Por quanto tempo você trabalhou lá?"],
      ["Why should I hire you?", "Por que eu deveria te contratar?"],
    ],
  },
  {
    id: "comparacao",
    label: "Comparações",
    title: "Comparações — mais que, melhor que",
    pattern: "[A] is more [adj] than [B] / [adj]-er than",
    rule: "Palavras curtas: adiciona -er (bigger, faster). Palavras longas: usa more (more complex, more expensive). Irregulares: good → better, bad → worse.",
    sentences: [
      ["This project is more complex than the last one.", "Este projeto é mais complexo que o último."],
      ["My English is better than it was last year.", "Meu inglês está melhor do que estava ano passado."],
      ["This tool is more expensive than Figma.", "Essa ferramenta é mais cara que o Figma."],
      ["Working remotely is easier than commuting.", "Trabalhar remotamente é mais fácil que se deslocar."],
      ["This client is bigger than the previous one.", "Esse cliente é maior que o anterior."],
      ["Design is more important than people think.", "Design é mais importante do que as pessoas pensam."],
      ["My new job is better than the old one.", "Meu novo emprego é melhor que o anterior."],
      ["This deadline is tighter than usual.", "Esse prazo é mais apertado que o normal."],
      ["This version is cleaner than the first draft.", "Essa versão está mais limpa que o primeiro rascunho."],
      ["Communication is harder than design sometimes.", "Comunicação é mais difícil que design às vezes."],
    ],
  },
  {
    id: "a_the",
    label: "A / The",
    title: "A / The — artigos",
    pattern: "a = qualquer um | the = específico",
    rule: "A/An → qualquer um, primeira menção. The → específico ou já mencionado. An → antes de som de vogal (an idea, an hour). Profissões: I am a designer.",
    sentences: [
      ["I work at a tech company.", "Eu trabalho em uma empresa de tecnologia."],
      ["The company has 200 employees.", "A empresa tem 200 funcionários."],
      ["I had a meeting this morning.", "Eu tive uma reunião essa manhã."],
      ["The meeting was very productive.", "A reunião foi muito produtiva."],
      ["I am a product designer.", "Eu sou product designer."],
      ["She had an idea for the project.", "Ela teve uma ideia para o projeto."],
      ["The idea was approved by the client.", "A ideia foi aprovada pelo cliente."],
      ["I sent a file to the team.", "Eu mandei um arquivo para o time."],
      ["The file needs to be updated.", "O arquivo precisa ser atualizado."],
      ["We have a new client this month.", "Nós temos um novo cliente esse mês."],
    ],
  },
  {
    id: "in_on_at",
    label: "In / On / At",
    title: "In / On / At — preposições de lugar e tempo",
    pattern: "at = ponto | in = dentro | on = projeto/dia",
    rule: "At → empresa, horário (at work, at 3pm). In → país, cidade, ano (in Brazil, in 2020). On → projeto, dia da semana (on a project, on Monday). From → origem (work from home).",
    sentences: [
      ["I work at a startup.", "Eu trabalho em uma startup."],
      ["I live in Brazil.", "Eu moro no Brasil."],
      ["I am working on a new project.", "Eu estou trabalhando em um projeto novo."],
      ["The meeting is at 3pm.", "A reunião é às 15h."],
      ["I work from home on Fridays.", "Eu trabalho de casa nas sextas."],
      ["I was born in São Paulo.", "Eu nasci em São Paulo."],
      ["We met on Monday.", "Nós nos encontramos na segunda-feira."],
      ["She is at the office today.", "Ela está no escritório hoje."],
      ["I started working on this in 2020.", "Eu comecei a trabalhar nisso em 2020."],
      ["I will be at the conference next week.", "Eu estarei na conferência semana que vem."],
    ],
  },
  {
    id: "for_since",
    label: "For / Since",
    title: "For / Since — duração de tempo",
    pattern: "for = duração | since = desde quando",
    rule: "For → quanto tempo durou (for 8 years, for 3 months). Since → quando começou (since 2016, since January).",
    sentences: [
      ["I have worked in design for 8 years.", "Eu trabalho em design há 8 anos."],
      ["I have lived in Sumaré since 2019.", "Eu moro em Sumaré desde 2019."],
      ["She has been a designer for 5 years.", "Ela é designer há 5 anos."],
      ["We have been partners since 2021.", "Nós somos parceiros desde 2021."],
      ["I have been studying English for 3 months.", "Eu estudo inglês há 3 meses."],
      ["He has worked there since he graduated.", "Ele trabalha lá desde que se formou."],
      ["I haven't changed jobs for 4 years.", "Eu não troco de emprego há 4 anos."],
      ["We have used Figma since 2018.", "Nós usamos Figma desde 2018."],
      ["She has been the manager for 2 years.", "Ela é gerente há 2 anos."],
      ["I have known him since we worked together.", "Eu o conheço desde quando trabalhamos juntos."],
    ],
  },
  {
    id: "have_exp",
    label: "Have + experiência",
    title: "Have + verbo no passado — experiência acumulada",
    pattern: "I have [verb-ed]...",
    rule: "Usado para falar de algo que aconteceu no passado e ainda tem impacto hoje. I have worked = eu já trabalhei / eu trabalho há X tempo.",
    sentences: [
      ["I have worked in design for 8 years.", "Eu trabalho em design há 8 anos."],
      ["I have built several design systems.", "Eu já construí vários design systems."],
      ["I have worked with international clients.", "Eu já trabalhei com clientes internacionais."],
      ["I have led teams of up to 10 people.", "Eu já liderei equipes de até 10 pessoas."],
      ["I have used Figma, Sketch, and Adobe XD.", "Eu já usei Figma, Sketch e Adobe XD."],
      ["I have worked in startups and big companies.", "Eu já trabalhei em startups e grandes empresas."],
      ["I have improved a lot this year.", "Eu melhorei muito esse ano."],
      ["I have learned a lot from my mistakes.", "Eu aprendi muito com meus erros."],
      ["I have never worked outside Brazil.", "Eu nunca trabalhei fora do Brasil."],
      ["I have always been passionate about design.", "Eu sempre fui apaixonado por design."],
    ],
  },
  {
    id: "phrasal",
    label: "Phrasal verbs",
    title: "Phrasal verbs — os mais usados no trabalho",
    pattern: "verbo + preposição = novo significado",
    rule: "A preposição muda tudo: give up = desistir, give in = ceder. look for = procurar, look up = pesquisar. set up = configurar, show up = aparecer.",
    sentences: [
      ["I gave up that project because it was toxic.", "Eu desisti daquele projeto porque era tóxico."],
      ["I'm looking for a new opportunity.", "Estou procurando uma nova oportunidade."],
      ["Can you set up the meeting for Thursday?", "Você pode marcar a reunião para quinta?"],
      ["He didn't show up to the presentation.", "Ele não apareceu para a apresentação."],
      ["I found out the problem was in the brief.", "Eu descobri que o problema estava no briefing."],
      ["Let's go on with the project.", "Vamos continuar com o projeto."],
      ["I need to log in to the platform.", "Eu preciso entrar na plataforma."],
      ["Please sign up before the event.", "Por favor, se cadastre antes do evento."],
      ["I need to look up the client's name.", "Eu preciso pesquisar o nome do cliente."],
      ["She turned down the job offer.", "Ela recusou a oferta de emprego."],
    ],
  },
];
