export type Sentence = [string, string];

export interface Category {
  id: string;
  label: string;
  title: string;
  pattern: string;
  rule: string;
  sentences: Sentence[];
}

export const categories: Category[] = [
  {
    id: "presente",
    label: "Presente rotina",
    title: "Presente — rotina e hábitos",
    pattern: "I [verb] as/at/in...",
    rule: "Usado para falar de rotina, profissão e hábitos. O verbo é simples, sem -ing.",
    sentences: [
      ["I work as a product designer.", "Eu trabalho como product designer."],
      ["I live in Brazil.", "Eu moro no Brasil."],
      ["I design digital products every day.", "Eu projeto produtos digitais todo dia."],
      ["I work at a tech company.", "Eu trabalho em uma empresa de tecnologia."],
      ["I collaborate with developers and stakeholders.", "Eu colaboro com desenvolvedores e stakeholders."],
      ["I use Figma to create prototypes.", "Eu uso Figma para criar protótipos."],
      ["I lead design projects from start to finish.", "Eu lidero projetos de design do início ao fim."],
      ["I speak Portuguese and some English.", "Eu falo português e um pouco de inglês."],
      ["I study English every week.", "Eu estudo inglês toda semana."],
      ["I work remotely most of the time.", "Eu trabalho remotamente na maior parte do tempo."],
      ["I manage my own schedule.", "Eu gerencio minha própria agenda."],
      ["I review designs before they go live.", "Eu reviso os designs antes de irem ao ar."],
      ["I present my work to clients.", "Eu apresento meu trabalho para clientes."],
      ["I take notes during every meeting.", "Eu anoto tudo durante cada reunião."],
      ["I work with cross-functional teams.", "Eu trabalho com equipes multifuncionais."],
      ["I run design sprints with the team.", "Eu conduzo design sprints com o time."],
      ["I give and receive feedback regularly.", "Eu dou e recebo feedback regularmente."],
      ["I iterate based on user research.", "Eu itero baseado em pesquisa com usuários."],
      ["I document all design decisions.", "Eu documento todas as decisões de design."],
      ["I keep my portfolio up to date.", "Eu mantenho meu portfólio atualizado."],
      ["I follow design trends and best practices.", "Eu acompanho tendências e boas práticas de design."],
      ["I work closely with the product team.", "Eu trabalho de perto com o time de produto."],
      ["I handle multiple projects at the same time.", "Eu gerencio vários projetos ao mesmo tempo."],
      ["I participate in usability tests.", "Eu participo de testes de usabilidade."],
      ["I create wireframes and prototypes.", "Eu crio wireframes e protótipos."],
      ["I deliver high-quality work consistently.", "Eu entrego trabalho de alta qualidade consistentemente."],
      ["I collaborate with the marketing team too.", "Eu também colaboro com o time de marketing."],
      ["I set priorities based on business goals.", "Eu defino prioridades com base nos objetivos de negócio."],
      ["I use data to support design decisions.", "Eu uso dados para embasar decisões de design."],
      ["I communicate progress to stakeholders.", "Eu comunico o progresso para os stakeholders."],
      ["I advocate for the user in every project.", "Eu defendo o usuário em cada projeto."],
      ["I learn something new almost every day.", "Eu aprendo algo novo quase todo dia."],
      ["I enjoy solving complex design problems.", "Eu gosto de resolver problemas complexos de design."],
      ["I work in an agile environment.", "Eu trabalho em um ambiente ágil."],
      ["I contribute to the design system.", "Eu contribuo para o design system."],
      ["I align with the team before starting a project.", "Eu me alinho com o time antes de começar um projeto."],
      ["I test my designs with real users.", "Eu testo meus designs com usuários reais."],
      ["I prioritize accessibility in my work.", "Eu priorizo acessibilidade no meu trabalho."],
      ["I share design updates in team meetings.", "Eu compartilho atualizações de design nas reuniões do time."],
      ["I ask questions when requirements are unclear.", "Eu faço perguntas quando os requisitos não estão claros."],
      ["I write design specs for developers.", "Eu escrevo especificações de design para os desenvolvedores."],
      ["I participate in sprint planning.", "Eu participo do planejamento do sprint."],
      ["I stay focused on the user's needs.", "Eu mantenho o foco nas necessidades do usuário."],
      ["I review competitor products for inspiration.", "Eu analiso produtos concorrentes por inspiração."],
      ["I mentor junior designers on the team.", "Eu oriento designers juniores no time."],
      ["I use component-based design in Figma.", "Eu uso design baseado em componentes no Figma."],
      ["I map user journeys to identify pain points.", "Eu mapeio jornadas do usuário para identificar pontos de dor."],
      ["I iterate quickly and learn from mistakes.", "Eu itero rapidamente e aprendo com os erros."],
      ["I build trust with clients through transparency.", "Eu construo confiança com clientes através da transparência."],
      ["I balance creativity with business constraints.", "Eu equilibro criatividade com restrições de negócio."],
    ],
  },
  {
    id: "presente_agora",
    label: "Presente agora",
    title: "Presente — o que está acontecendo agora",
    pattern: "I am [verb]-ing...",
    rule: "Usado para falar do que está acontecendo nesse momento. Sempre usa am/is/are + verbo-ing.",
    sentences: [
      ["I am working on a new project.", "Eu estou trabalhando em um projeto novo."],
      ["I am learning English right now.", "Eu estou aprendendo inglês agora."],
      ["I am building a design system.", "Eu estou construindo um design system."],
      ["I am talking to a client.", "Eu estou falando com um cliente."],
      ["I am improving my skills.", "Eu estou melhorando minhas habilidades."],
      ["I am living in Sumaré.", "Eu estou morando em Sumaré."],
      ["I am working on a presentation.", "Eu estou trabalhando em uma apresentação."],
      ["I am reading about UX research.", "Eu estou lendo sobre UX research."],
      ["I am looking for new opportunities.", "Eu estou procurando novas oportunidades."],
      ["I am growing as a professional.", "Eu estou crescendo como profissional."],
      ["I am reviewing the latest designs.", "Eu estou revisando os designs mais recentes."],
      ["I am preparing for a job interview.", "Eu estou me preparando para uma entrevista de emprego."],
      ["I am redesigning the onboarding flow.", "Eu estou redesenhando o fluxo de onboarding."],
      ["I am taking an online course.", "Eu estou fazendo um curso online."],
      ["I am documenting the design decisions.", "Eu estou documentando as decisões de design."],
      ["I am waiting for client feedback.", "Eu estou esperando o feedback do cliente."],
      ["I am updating my portfolio.", "Eu estou atualizando meu portfólio."],
      ["I am working with a new team.", "Eu estou trabalhando com um time novo."],
      ["I am attending a design conference.", "Eu estou participando de uma conferência de design."],
      ["I am exploring new design tools.", "Eu estou explorando novas ferramentas de design."],
      ["I am collaborating with developers.", "Eu estou colaborando com os desenvolvedores."],
      ["I am running a usability test.", "Eu estou conduzindo um teste de usabilidade."],
      ["I am writing user stories.", "Eu estou escrevendo histórias de usuário."],
      ["I am sketching ideas on paper.", "Eu estou esboçando ideias no papel."],
      ["I am planning the next sprint.", "Eu estou planejando o próximo sprint."],
      ["I am fixing some issues in the prototype.", "Eu estou corrigindo alguns problemas no protótipo."],
      ["I am aligning with the product manager.", "Eu estou me alinhando com o product manager."],
      ["I am setting up a design review.", "Eu estou organizando uma revisão de design."],
      ["I am building a new component library.", "Eu estou construindo uma nova biblioteca de componentes."],
      ["I am testing my designs on mobile.", "Eu estou testando meus designs no celular."],
      ["I am getting better at public speaking.", "Eu estou melhorando em falar em público."],
      ["I am trying to understand the user's pain points.", "Eu estou tentando entender os pontos de dor do usuário."],
      ["I am presenting my work to the board.", "Eu estou apresentando meu trabalho para a diretoria."],
      ["I am mapping the current user journey.", "Eu estou mapeando a jornada atual do usuário."],
      ["I am transitioning to a senior role.", "Eu estou transitando para um cargo sênior."],
      ["I am helping a junior designer on the team.", "Eu estou ajudando um designer júnior no time."],
      ["I am refining the visual identity.", "Eu estou refinando a identidade visual."],
      ["I am pushing myself out of my comfort zone.", "Eu estou me desafiando a sair da zona de conforto."],
      ["I am starting to feel more confident in English.", "Eu estou começando a me sentir mais confiante em inglês."],
      ["I am delivering results faster than before.", "Eu estou entregando resultados mais rápido do que antes."],
      ["I am working on a tight deadline.", "Eu estou trabalhando com um prazo apertado."],
      ["I am gathering insights from user interviews.", "Eu estou coletando insights de entrevistas com usuários."],
      ["I am balancing multiple priorities.", "Eu estou equilibrando múltiplas prioridades."],
      ["I am tracking design metrics.", "Eu estou acompanhando métricas de design."],
      ["I am participating in a design challenge.", "Eu estou participando de um desafio de design."],
      ["I am becoming more strategic in my thinking.", "Eu estou me tornando mais estratégico no meu raciocínio."],
      ["I am creating a style guide for the project.", "Eu estou criando um guia de estilo para o projeto."],
      ["I am finishing the last round of revisions.", "Eu estou finalizando a última rodada de revisões."],
      ["I am setting up design tokens.", "Eu estou configurando os design tokens."],
      ["I am expanding my network in the industry.", "Eu estou expandindo minha rede na indústria."],
    ],
  },
  {
    id: "passado",
    label: "Passado simples",
    title: "Passado — o que já aconteceu",
    pattern: "I [verb-ed / irregular] at/in/for...",
    rule: "Verbos regulares recebem -ed. Irregulares mudam a forma inteira. Usado para falar de eventos concluídos.",
    sentences: [
      ["I worked at a startup for 3 years.", "Eu trabalhei em uma startup por 3 anos."],
      ["I designed the entire app from scratch.", "Eu projetei o app inteiro do zero."],
      ["I lived in São Paulo for a while.", "Eu morei em São Paulo por um tempo."],
      ["I led a team of five people.", "Eu liderei uma equipe de cinco pessoas."],
      ["I built a design system for the company.", "Eu construí um design system para a empresa."],
      ["I finished the project on time.", "Eu terminei o projeto no prazo."],
      ["I worked with international clients.", "Eu trabalhei com clientes internacionais."],
      ["I started my career as a junior designer.", "Eu comecei minha carreira como designer junior."],
      ["I moved to Sumaré two years ago.", "Eu me mudei para Sumaré há dois anos."],
      ["I gave up that job because it was toxic.", "Eu desisti daquele emprego porque era tóxico."],
      ["I presented my work at a conference.", "Eu apresentei meu trabalho em uma conferência."],
      ["I redesigned the entire checkout flow.", "Eu redesenhei todo o fluxo de checkout."],
      ["I joined the company as a UX lead.", "Eu entrei na empresa como líder de UX."],
      ["I delivered the project ahead of schedule.", "Eu entreguei o projeto antes do prazo."],
      ["I learned a lot from that experience.", "Eu aprendi muito com aquela experiência."],
      ["I managed a design team for the first time.", "Eu gerenciei um time de design pela primeira vez."],
      ["I created a brand identity for a startup.", "Eu criei uma identidade de marca para uma startup."],
      ["I ran multiple usability tests.", "Eu conduzi vários testes de usabilidade."],
      ["I collaborated with teams across different time zones.", "Eu colaborei com times em fusos horários diferentes."],
      ["I improved the app's conversion rate.", "Eu melhorei a taxa de conversão do aplicativo."],
      ["I launched a new product last year.", "Eu lancei um produto novo no ano passado."],
      ["I received very positive feedback from users.", "Eu recebi feedback muito positivo dos usuários."],
      ["I trained junior designers on best practices.", "Eu treinei designers juniores em boas práticas."],
      ["I took ownership of the entire design process.", "Eu assumi a responsabilidade de todo o processo de design."],
      ["I spent two years on that project.", "Eu passei dois anos naquele projeto."],
      ["I solved a major usability problem.", "Eu resolvi um grande problema de usabilidade."],
      ["I wrote the design guidelines for the team.", "Eu escrevi as diretrizes de design para o time."],
      ["I contributed to the company's growth.", "Eu contribuí para o crescimento da empresa."],
      ["I reduced the onboarding drop-off rate.", "Eu reduzi a taxa de abandono do onboarding."],
      ["I worked closely with the CEO on the product vision.", "Eu trabalhei de perto com o CEO na visão do produto."],
      ["I implemented a new design review process.", "Eu implementei um novo processo de revisão de design."],
      ["I moved from junior to senior in two years.", "Eu fui de júnior a sênior em dois anos."],
      ["I handled all the design for that product launch.", "Eu cuidei de todo o design para aquele lançamento de produto."],
      ["I built the first version of the design system.", "Eu construí a primeira versão do design system."],
      ["I left the company on good terms.", "Eu saí da empresa em bons termos."],
      ["I won a design award for that project.", "Eu ganhei um prêmio de design por aquele projeto."],
      ["I shipped over 20 features in one year.", "Eu lancei mais de 20 funcionalidades em um ano."],
      ["I interviewed over 30 users for that research.", "Eu entrevistei mais de 30 usuários para aquela pesquisa."],
      ["I grew the design team from 2 to 8 people.", "Eu fiz o time de design crescer de 2 para 8 pessoas."],
      ["I introduced design thinking to the company.", "Eu introduzi o design thinking na empresa."],
      ["I saved the project by catching a critical error early.", "Eu salvei o projeto ao identificar um erro crítico cedo."],
      ["I negotiated the project scope with the client.", "Eu negociei o escopo do projeto com o cliente."],
      ["I helped the team ship the product on time.", "Eu ajudei o time a lançar o produto no prazo."],
      ["I documented all user research findings.", "Eu documentei todos os resultados da pesquisa com usuários."],
      ["I presented the new design system to the whole company.", "Eu apresentei o novo design system para toda a empresa."],
      ["I worked on three products simultaneously.", "Eu trabalhei em três produtos simultaneamente."],
      ["I built a strong relationship with the engineering team.", "Eu construí um relacionamento forte com o time de engenharia."],
      ["I discovered a key insight during user testing.", "Eu descobri um insight importante durante os testes com usuários."],
      ["I increased user satisfaction scores by 30%.", "Eu aumentei os índices de satisfação dos usuários em 30%."],
      ["I set up the design culture from scratch.", "Eu criei a cultura de design do zero."],
    ],
  },
  {
    id: "passado_neg",
    label: "Passado negativo",
    title: "Passado — negativa com didn't",
    pattern: "I didn't [verbo normal]...",
    rule: "Depois de didn't o verbo sempre volta ao normal, sem -ed. Mesma regra para todas as pessoas.",
    sentences: [
      ["I didn't finish the project on time.", "Eu não terminei o projeto no prazo."],
      ["I didn't work as a developer.", "Eu não trabalhei como desenvolvedor."],
      ["I didn't leave because of money.", "Eu não saí por causa de dinheiro."],
      ["I didn't know how to code before.", "Eu não sabia programar antes."],
      ["I didn't speak English at that time.", "Eu não falava inglês naquela época."],
      ["I didn't like that project.", "Eu não gostei daquele projeto."],
      ["I didn't have a team to help me.", "Eu não tinha equipe para me ajudar."],
      ["I didn't expect that result.", "Eu não esperava aquele resultado."],
      ["I didn't give up even when it was hard.", "Eu não desisti mesmo quando foi difícil."],
      ["I didn't see that problem coming.", "Eu não vi aquele problema vindo."],
      ["I didn't agree with the decision.", "Eu não concordei com a decisão."],
      ["I didn't have enough experience at the time.", "Eu não tinha experiência suficiente na época."],
      ["I didn't understand the requirements.", "Eu não entendi os requisitos."],
      ["I didn't get the promotion that year.", "Eu não fui promovido naquele ano."],
      ["I didn't realize how complex it would be.", "Eu não percebi o quão complexo seria."],
      ["I didn't deliver the best work that week.", "Eu não entreguei o melhor trabalho naquela semana."],
      ["I didn't communicate clearly enough.", "Eu não me comuniquei de forma clara o suficiente."],
      ["I didn't ask for help when I should have.", "Eu não pedi ajuda quando deveria."],
      ["I didn't meet the client's expectations.", "Eu não atendi às expectativas do cliente."],
      ["I didn't have time to test the design.", "Eu não tinha tempo para testar o design."],
      ["I didn't receive any feedback on that work.", "Eu não recebi nenhum feedback sobre aquele trabalho."],
      ["I didn't know the team was struggling.", "Eu não sabia que o time estava com dificuldades."],
      ["I didn't use the right tool for that task.", "Eu não usei a ferramenta certa para aquela tarefa."],
      ["I didn't take notes during the meeting.", "Eu não anotei nada durante a reunião."],
      ["I didn't follow the design guidelines.", "Eu não segui as diretrizes de design."],
      ["I didn't attend the kickoff meeting.", "Eu não participei da reunião de kickoff."],
      ["I didn't manage my time well that week.", "Eu não gerenciei bem meu tempo naquela semana."],
      ["I didn't think about edge cases.", "Eu não pensei nos casos extremos."],
      ["I didn't review the copy before publishing.", "Eu não revisei o texto antes de publicar."],
      ["I didn't set clear expectations with the client.", "Eu não estabeleci expectativas claras com o cliente."],
      ["I didn't document the final design decisions.", "Eu não documentei as decisões finais de design."],
      ["I didn't push back on the unrealistic deadline.", "Eu não contestei o prazo irreal."],
      ["I didn't involve the developers early enough.", "Eu não envolvi os desenvolvedores cedo o suficiente."],
      ["I didn't prioritize accessibility in that project.", "Eu não priorizei acessibilidade naquele projeto."],
      ["I didn't validate the idea before building it.", "Eu não validei a ideia antes de construí-la."],
      ["I didn't present my work confidently.", "Eu não apresentei meu trabalho com confiança."],
      ["I didn't back up my files before the crash.", "Eu não fiz backup dos arquivos antes da falha."],
      ["I didn't track the project's progress properly.", "Eu não acompanhei o progresso do projeto adequadamente."],
      ["I didn't notice the design inconsistencies.", "Eu não percebi as inconsistências de design."],
      ["I didn't realize I was overcomplicating it.", "Eu não percebi que estava complicando demais."],
      ["I didn't feel confident presenting in English.", "Eu não me sentia confiante apresentando em inglês."],
      ["I didn't apply for that job because I was scared.", "Eu não me candidatei àquele emprego porque estava com medo."],
      ["I didn't sleep well the night before the presentation.", "Eu não dormi bem na noite antes da apresentação."],
      ["I didn't update the design after the last review.", "Eu não atualizei o design depois da última revisão."],
      ["I didn't include the stakeholders in the process.", "Eu não incluí os stakeholders no processo."],
      ["I didn't think the change would cause so many issues.", "Eu não achei que a mudança causaria tantos problemas."],
      ["I didn't read the brief carefully enough.", "Eu não li o briefing com atenção suficiente."],
      ["I didn't celebrate small wins back then.", "Eu não comemorava pequenas conquistas naquela época."],
      ["I didn't realize how important soft skills were.", "Eu não percebia o quão importantes eram as soft skills."],
      ["I didn't have a mentor to guide me.", "Eu não tinha um mentor para me guiar."],
    ],
  },
  {
    id: "futuro_will",
    label: "Futuro — will",
    title: "Futuro — decisão na hora ou promessa",
    pattern: "I will [verbo direto]...",
    rule: "Will não usa 'to' depois. Vai direto pro verbo. Usado para decisões tomadas agora ou promessas.",
    sentences: [
      ["I will send you the file tomorrow.", "Eu vou te mandar o arquivo amanhã."],
      ["I will finish the project this week.", "Eu vou terminar o projeto essa semana."],
      ["I will improve my English this year.", "Eu vou melhorar meu inglês esse ano."],
      ["I will call you later.", "Eu vou te ligar mais tarde."],
      ["I will help you with the design.", "Eu vou te ajudar com o design."],
      ["I will learn new tools next month.", "Eu vou aprender novas ferramentas no próximo mês."],
      ["I will lead the next project.", "Eu vou liderar o próximo projeto."],
      ["I will share the presentation today.", "Eu vou compartilhar a apresentação hoje."],
      ["I will not give up on this.", "Eu não vou desistir disso."],
      ["I will start studying tomorrow.", "Eu vou começar a estudar amanhã."],
      ["I will review your work by end of day.", "Eu vou revisar seu trabalho até o final do dia."],
      ["I will set up a meeting with the team.", "Eu vou marcar uma reunião com o time."],
      ["I will fix that bug right now.", "Eu vou corrigir aquele erro agora."],
      ["I will make sure we meet the deadline.", "Eu vou garantir que cumpriremos o prazo."],
      ["I will update you as soon as I know.", "Eu vou te atualizar assim que souber."],
      ["I will take on more responsibility next year.", "Eu vou assumir mais responsabilidade no próximo ano."],
      ["I will not miss that deadline again.", "Eu não vou perder aquele prazo novamente."],
      ["I will try a different approach.", "Eu vou tentar uma abordagem diferente."],
      ["I will present the final version on Friday.", "Eu vou apresentar a versão final na sexta."],
      ["I will speak more English in meetings.", "Eu vou falar mais inglês nas reuniões."],
      ["I will apply for that position.", "Eu vou me candidatar para aquela posição."],
      ["I will give you honest feedback.", "Eu vou te dar um feedback honesto."],
      ["I will create a new version of the prototype.", "Eu vou criar uma nova versão do protótipo."],
      ["I will not let the team down.", "Eu não vou decepcionar o time."],
      ["I will push myself to grow faster.", "Eu vou me desafiar a crescer mais rápido."],
      ["I will document everything this time.", "Eu vou documentar tudo desta vez."],
      ["I will be more proactive in meetings.", "Eu vou ser mais proativo nas reuniões."],
      ["I will ask for feedback before finalizing.", "Eu vou pedir feedback antes de finalizar."],
      ["I will redesign the landing page next sprint.", "Eu vou redesenhar a landing page no próximo sprint."],
      ["I will not accept scope creep without discussion.", "Eu não vou aceitar escopo extra sem discussão."],
      ["I will prepare better for this presentation.", "Eu vou me preparar melhor para essa apresentação."],
      ["I will reach out to that recruiter.", "Eu vou entrar em contato com aquele recrutador."],
      ["I will learn how to better communicate with engineers.", "Eu vou aprender a me comunicar melhor com os engenheiros."],
      ["I will set clearer goals this quarter.", "Eu vou definir metas mais claras nesse trimestre."],
      ["I will work on my public speaking skills.", "Eu vou trabalhar minhas habilidades de falar em público."],
      ["I will prioritize the most impactful tasks.", "Eu vou priorizar as tarefas de maior impacto."],
      ["I will take time to celebrate this win.", "Eu vou tirar um tempo para comemorar essa conquista."],
      ["I will build something I'm proud of.", "Eu vou construir algo do qual me orgulharei."],
      ["I will follow up with the client next week.", "Eu vou fazer um follow-up com o cliente semana que vem."],
      ["I will make this version cleaner and simpler.", "Eu vou deixar essa versão mais limpa e simples."],
      ["I will help the team improve their design skills.", "Eu vou ajudar o time a melhorar suas habilidades de design."],
      ["I will be ready for the interview.", "Eu vou estar pronto para a entrevista."],
      ["I will ship this feature by the end of the month.", "Eu vou lançar essa funcionalidade até o fim do mês."],
      ["I will not overthink this anymore.", "Eu não vou mais pensar demais nisso."],
      ["I will trust my process.", "Eu vou confiar no meu processo."],
      ["I will accept this challenge.", "Eu vou aceitar esse desafio."],
      ["I will start with the most critical screen.", "Eu vou começar com a tela mais crítica."],
      ["I will use more data in my next presentation.", "Eu vou usar mais dados na minha próxima apresentação."],
      ["I will keep learning no matter what.", "Eu vou continuar aprendendo aconteça o que acontecer."],
      ["I will find a solution for this problem.", "Eu vou encontrar uma solução para esse problema."],
    ],
  },
  {
    id: "futuro_going",
    label: "Futuro — going to",
    title: "Futuro — plano já decidido",
    pattern: "I am going to [verbo]...",
    rule: "Usado para planos que já foram decididos antes. Diferente do will, que é decisão na hora.",
    sentences: [
      ["I am going to start a new project next week.", "Eu vou começar um projeto novo semana que vem."],
      ["I am going to travel to Europe next year.", "Eu vou viajar para a Europa ano que vem."],
      ["I am going to present my work to the team.", "Eu vou apresentar meu trabalho para o time."],
      ["I am going to learn UX writing.", "Eu vou aprender UX writing."],
      ["I am going to change jobs this year.", "Eu vou mudar de emprego esse ano."],
      ["I am going to build my portfolio.", "Eu vou construir meu portfólio."],
      ["I am going to take an English course.", "Eu vou fazer um curso de inglês."],
      ["I am going to work from home next week.", "Eu vou trabalhar de casa semana que vem."],
      ["I am going to talk to my manager tomorrow.", "Eu vou falar com meu gestor amanhã."],
      ["I am going to move to a bigger city.", "Eu vou me mudar para uma cidade maior."],
      ["I am going to redesign the app from scratch.", "Eu vou redesenhar o app do zero."],
      ["I am going to apply for a senior position.", "Eu vou me candidatar para uma posição sênior."],
      ["I am going to attend a UX conference.", "Eu vou participar de uma conferência de UX."],
      ["I am going to update my LinkedIn profile.", "Eu vou atualizar meu perfil no LinkedIn."],
      ["I am going to run a design workshop.", "Eu vou conduzir um workshop de design."],
      ["I am going to hire a junior designer.", "Eu vou contratar um designer júnior."],
      ["I am going to pitch a new idea to the team.", "Eu vou apresentar uma nova ideia para o time."],
      ["I am going to read more books about product design.", "Eu vou ler mais livros sobre product design."],
      ["I am going to speak at a local meetup.", "Eu vou falar em um meetup local."],
      ["I am going to improve my Figma skills.", "Eu vou melhorar minhas habilidades no Figma."],
      ["I am going to set up a personal design challenge.", "Eu vou criar um desafio pessoal de design."],
      ["I am going to ask for a salary raise.", "Eu vou pedir um aumento de salário."],
      ["I am going to create a case study for this project.", "Eu vou criar um case study para esse projeto."],
      ["I am going to review the design system next quarter.", "Eu vou revisar o design system no próximo trimestre."],
      ["I am going to meet with the stakeholders on Monday.", "Eu vou me reunir com os stakeholders na segunda."],
      ["I am going to focus on accessibility this month.", "Eu vou focar em acessibilidade esse mês."],
      ["I am going to dedicate more time to user research.", "Eu vou dedicar mais tempo à pesquisa com usuários."],
      ["I am going to stop procrastinating on that task.", "Eu vou parar de procrastinar naquela tarefa."],
      ["I am going to get better at giving presentations.", "Eu vou melhorar em dar apresentações."],
      ["I am going to start a side project.", "Eu vou começar um projeto paralelo."],
      ["I am going to organize all my Figma files.", "Eu vou organizar todos os meus arquivos do Figma."],
      ["I am going to launch my personal website.", "Eu vou lançar meu site pessoal."],
      ["I am going to practice English every day.", "Eu vou praticar inglês todo dia."],
      ["I am going to document my design process better.", "Eu vou documentar melhor meu processo de design."],
      ["I am going to schedule a feedback session.", "Eu vou agendar uma sessão de feedback."],
      ["I am going to build a stronger professional network.", "Eu vou construir uma rede profissional mais forte."],
      ["I am going to define clearer KPIs for the project.", "Eu vou definir KPIs mais claros para o projeto."],
      ["I am going to onboard the new designer next week.", "Eu vou fazer o onboarding do novo designer semana que vem."],
      ["I am going to invest more in my career development.", "Eu vou investir mais no meu desenvolvimento de carreira."],
      ["I am going to simplify the checkout flow.", "Eu vou simplificar o fluxo de checkout."],
      ["I am going to write a blog post about my process.", "Eu vou escrever um post sobre meu processo."],
      ["I am going to improve team communication.", "Eu vou melhorar a comunicação do time."],
      ["I am going to prioritize rest and balance.", "Eu vou priorizar descanso e equilíbrio."],
      ["I am going to take a design course next month.", "Eu vou fazer um curso de design no próximo mês."],
      ["I am going to launch the beta version next Thursday.", "Eu vou lançar a versão beta na próxima quinta."],
      ["I am going to explore motion design.", "Eu vou explorar motion design."],
      ["I am going to share my learnings with the team.", "Eu vou compartilhar meus aprendizados com o time."],
      ["I am going to create a better onboarding experience.", "Eu vou criar uma experiência de onboarding melhor."],
      ["I am going to negotiate a remote work arrangement.", "Eu vou negociar um acordo de trabalho remoto."],
      ["I am going to build something meaningful.", "Eu vou construir algo com significado."],
    ],
  },
  {
    id: "do_does",
    label: "Do / Does",
    title: "Do / Does — perguntas e negativas no presente",
    pattern: "Do/Does + sujeito + verbo?",
    rule: "Do → I, You, We, They. Does → He, She, It. Com does/doesn't o verbo fica no normal, sem -s no final.",
    sentences: [
      ["Do you work remotely?", "Você trabalha remotamente?"],
      ["Does she have experience in UX?", "Ela tem experiência em UX?"],
      ["Do they use Figma?", "Eles usam Figma?"],
      ["Does he speak English?", "Ele fala inglês?"],
      ["Do you have a portfolio?", "Você tem um portfólio?"],
      ["I don't work on weekends.", "Eu não trabalho nos fins de semana."],
      ["She doesn't like that design.", "Ela não gosta daquele design."],
      ["They don't use that tool.", "Eles não usam aquela ferramenta."],
      ["He doesn't have a LinkedIn.", "Ele não tem LinkedIn."],
      ["We don't work with that client anymore.", "Nós não trabalhamos mais com aquele cliente."],
      ["Do you have a design system in place?", "Você tem um design system implementado?"],
      ["Does the team follow a process?", "O time segue um processo?"],
      ["Do you give feedback often?", "Você dá feedback com frequência?"],
      ["Does he lead the design team?", "Ele lidera o time de design?"],
      ["Do they have a product roadmap?", "Eles têm um roadmap de produto?"],
      ["I don't agree with that decision.", "Eu não concordo com aquela decisão."],
      ["She doesn't work on Fridays.", "Ela não trabalha nas sextas."],
      ["He doesn't respond to feedback well.", "Ele não responde bem ao feedback."],
      ["We don't have enough resources.", "Nós não temos recursos suficientes."],
      ["They don't have a clear vision.", "Eles não têm uma visão clara."],
      ["Do you collaborate with the marketing team?", "Você colabora com o time de marketing?"],
      ["Does she manage the product roadmap?", "Ela gerencia o roadmap de produto?"],
      ["Do you track user behavior?", "Você acompanha o comportamento do usuário?"],
      ["Does he code his own prototypes?", "Ele programa seus próprios protótipos?"],
      ["Do you use data to make design decisions?", "Você usa dados para tomar decisões de design?"],
      ["I don't have time for that right now.", "Eu não tenho tempo para isso agora."],
      ["She doesn't know how to use Figma.", "Ela não sabe usar o Figma."],
      ["He doesn't prioritize accessibility.", "Ele não prioriza acessibilidade."],
      ["We don't ship without a design review.", "Nós não lançamos sem revisão de design."],
      ["They don't involve designers early enough.", "Eles não envolvem os designers cedo o suficiente."],
      ["Do you feel comfortable presenting in English?", "Você se sente confortável apresentando em inglês?"],
      ["Does the client have a brand guide?", "O cliente tem um guia de marca?"],
      ["Do you run retrospectives?", "Você conduz retrospectivas?"],
      ["Does she understand the technical constraints?", "Ela entende as restrições técnicas?"],
      ["Do you mentor anyone on the team?", "Você é mentor de alguém no time?"],
      ["I don't think that solution will work.", "Eu não acho que essa solução vai funcionar."],
      ["She doesn't communicate her ideas clearly.", "Ela não comunica suas ideias com clareza."],
      ["He doesn't take feedback personally.", "Ele não leva o feedback para o lado pessoal."],
      ["We don't always agree, but we respect each other.", "Nós nem sempre concordamos, mas nos respeitamos."],
      ["They don't have a dedicated designer.", "Eles não têm um designer dedicado."],
      ["Do you enjoy your current role?", "Você gosta do seu cargo atual?"],
      ["Does the product have a clear target audience?", "O produto tem um público-alvo claro?"],
      ["Do you use a component library?", "Você usa uma biblioteca de componentes?"],
      ["Does he set realistic expectations?", "Ele define expectativas realistas?"],
      ["Do you have 1:1s with your manager?", "Você tem 1:1s com o seu gestor?"],
      ["I don't skip the research phase.", "Eu não pulo a fase de pesquisa."],
      ["She doesn't rush through the design process.", "Ela não apressa o processo de design."],
      ["He doesn't handle pressure well.", "Ele não lida bem com pressão."],
      ["We don't build features without validating first.", "Nós não desenvolvemos funcionalidades sem validar antes."],
      ["They don't understand the value of UX.", "Eles não entendem o valor do UX."],
    ],
  },
  {
    id: "did",
    label: "Did / Didn't",
    title: "Did / Didn't — perguntas e negativas no passado",
    pattern: "Did + sujeito + verbo? / I didn't + verbo",
    rule: "Did é igual para todo mundo no passado. Depois de did/didn't o verbo sempre volta ao normal.",
    sentences: [
      ["Did you work on that project?", "Você trabalhou naquele projeto?"],
      ["Did she finish the design on time?", "Ela terminou o design no prazo?"],
      ["Did they approve the proposal?", "Eles aprovaram a proposta?"],
      ["Did he leave the company?", "Ele saiu da empresa?"],
      ["Did you have a good experience there?", "Você teve uma boa experiência lá?"],
      ["I didn't finish the project on time.", "Eu não terminei o projeto no prazo."],
      ["She didn't like the feedback.", "Ela não gostou do feedback."],
      ["They didn't approve the design.", "Eles não aprovaram o design."],
      ["He didn't show up to the meeting.", "Ele não apareceu para a reunião."],
      ["We didn't have enough time.", "Nós não tínhamos tempo suficiente."],
      ["Did you attend the kickoff meeting?", "Você participou da reunião de kickoff?"],
      ["Did she lead the design team?", "Ela liderou o time de design?"],
      ["Did they give you feedback?", "Eles te deram feedback?"],
      ["Did he understand the requirements?", "Ele entendeu os requisitos?"],
      ["Did you get a chance to test the prototype?", "Você teve a chance de testar o protótipo?"],
      ["I didn't understand the brief.", "Eu não entendi o briefing."],
      ["She didn't present her work confidently.", "Ela não apresentou seu trabalho com confiança."],
      ["They didn't review the design before shipping.", "Eles não revisaram o design antes de lançar."],
      ["He didn't document the changes.", "Ele não documentou as mudanças."],
      ["We didn't involve the users in the process.", "Nós não envolvemos os usuários no processo."],
      ["Did you run any user research?", "Você conduziu alguma pesquisa com usuários?"],
      ["Did she work at that company before?", "Ela trabalhou naquela empresa antes?"],
      ["Did they deliver on time?", "Eles entregaram no prazo?"],
      ["Did he know about the deadline change?", "Ele sabia sobre a mudança de prazo?"],
      ["Did you enjoy working on that project?", "Você gostou de trabalhar naquele projeto?"],
      ["I didn't set clear expectations.", "Eu não defini expectativas claras."],
      ["She didn't ask for help when she needed it.", "Ela não pediu ajuda quando precisou."],
      ["They didn't consider accessibility.", "Eles não consideraram acessibilidade."],
      ["He didn't back up his files.", "Ele não fez backup dos arquivos."],
      ["We didn't test on mobile devices.", "Nós não testamos em dispositivos móveis."],
      ["Did you get feedback from the stakeholders?", "Você recebeu feedback dos stakeholders?"],
      ["Did she handle the client well?", "Ela lidou bem com o cliente?"],
      ["Did they use a design system?", "Eles usaram um design system?"],
      ["Did he take the project seriously?", "Ele levou o projeto a sério?"],
      ["Did you feel supported by the team?", "Você se sentiu apoiado pelo time?"],
      ["I didn't prioritize the right things.", "Eu não priorizei as coisas certas."],
      ["She didn't like working under pressure.", "Ela não gostava de trabalhar sob pressão."],
      ["They didn't align on the vision.", "Eles não se alinharam na visão."],
      ["He didn't communicate the scope clearly.", "Ele não comunicou o escopo claramente."],
      ["We didn't have enough data to decide.", "Nós não tínhamos dados suficientes para decidir."],
      ["Did you ever work with international clients?", "Você já trabalhou com clientes internacionais?"],
      ["Did she join the team early in the project?", "Ela entrou no time no início do projeto?"],
      ["Did they change the requirements mid-project?", "Eles mudaram os requisitos no meio do projeto?"],
      ["Did he help onboard new designers?", "Ele ajudou no onboarding de novos designers?"],
      ["Did you have a good relationship with your manager?", "Você tinha um bom relacionamento com seu gestor?"],
      ["I didn't have a clear direction at first.", "Eu não tinha uma direção clara no início."],
      ["She didn't contribute much to that project.", "Ela não contribuiu muito para aquele projeto."],
      ["They didn't give enough context in the brief.", "Eles não deram contexto suficiente no briefing."],
      ["He didn't respect the design process.", "Ele não respeitou o processo de design."],
      ["We didn't celebrate the launch properly.", "Nós não comemoramos o lançamento adequadamente."],
    ],
  },
  {
    id: "have_has",
    label: "Have / Has",
    title: "Have / Has — ter e experiência",
    pattern: "I have / She has + [substantivo ou verbo no passado]",
    rule: "Have → I, You, We, They. Has → He, She, It. Como experiência: I have worked here for 8 years.",
    sentences: [
      ["I have 8 years of experience.", "Eu tenho 8 anos de experiência."],
      ["She has a strong portfolio.", "Ela tem um portfólio forte."],
      ["We have a meeting at 3pm.", "Nós temos uma reunião às 15h."],
      ["He has a lot of experience in UX.", "Ele tem muita experiência em UX."],
      ["They have a new client.", "Eles têm um novo cliente."],
      ["I have worked here for 2 years.", "Eu trabalho aqui há 2 anos."],
      ["She has already finished the project.", "Ela já terminou o projeto."],
      ["We have never missed a deadline.", "Nós nunca perdemos um prazo."],
      ["He has built three design systems.", "Ele já construiu três design systems."],
      ["They have grown a lot this year.", "Eles cresceram muito esse ano."],
      ["I have a meeting with the client tomorrow.", "Eu tenho uma reunião com o cliente amanhã."],
      ["She has a clear vision for the product.", "Ela tem uma visão clara para o produto."],
      ["We have a solid design process.", "Nós temos um processo de design sólido."],
      ["He has excellent communication skills.", "Ele tem excelentes habilidades de comunicação."],
      ["They have a large user base.", "Eles têm uma base de usuários grande."],
      ["I have experience with design systems.", "Eu tenho experiência com design systems."],
      ["She has worked with many different clients.", "Ela já trabalhou com muitos clientes diferentes."],
      ["We have launched three products this year.", "Nós lançamos três produtos esse ano."],
      ["He has a background in graphic design.", "Ele tem formação em design gráfico."],
      ["They have a very tight deadline.", "Eles têm um prazo muito apertado."],
      ["I have improved my presentation skills.", "Eu melhorei minhas habilidades de apresentação."],
      ["She has a unique design style.", "Ela tem um estilo de design único."],
      ["We have a diverse and talented team.", "Nós temos um time diverso e talentoso."],
      ["He has managed multiple projects at once.", "Ele já gerenciou múltiplos projetos ao mesmo tempo."],
      ["They have invested in design culture.", "Eles investiram em cultura de design."],
      ["I have learned from every project I worked on.", "Eu aprendi com cada projeto em que trabalhei."],
      ["She has a strong sense of visual hierarchy.", "Ela tem um senso forte de hierarquia visual."],
      ["We have a clear product roadmap.", "Nós temos um roadmap de produto claro."],
      ["He has a talent for solving complex problems.", "Ele tem talento para resolver problemas complexos."],
      ["They have high standards for quality.", "Eles têm altos padrões de qualidade."],
      ["I have a habit of asking a lot of questions.", "Eu tenho o hábito de fazer muitas perguntas."],
      ["She has been leading the team for two years.", "Ela lidera o time há dois anos."],
      ["We have a culture of continuous improvement.", "Nós temos uma cultura de melhoria contínua."],
      ["He has always been passionate about user experience.", "Ele sempre foi apaixonado por experiência do usuário."],
      ["They have received very positive user feedback.", "Eles receberam feedback muito positivo dos usuários."],
      ["I have a lot to learn, and that's exciting.", "Eu tenho muito a aprender, e isso é empolgante."],
      ["She has taken ownership of the entire product.", "Ela assumiu a responsabilidade de todo o produto."],
      ["We have aligned on the strategy.", "Nós nos alinhamos na estratégia."],
      ["He has deep knowledge of accessibility standards.", "Ele tem profundo conhecimento de padrões de acessibilidade."],
      ["They have a product-led growth strategy.", "Eles têm uma estratégia de crescimento orientada por produto."],
      ["I have never been afraid to share my opinions.", "Eu nunca tive medo de compartilhar minhas opiniões."],
      ["She has created components used by the entire team.", "Ela criou componentes usados por todo o time."],
      ["We have reduced the time to ship by 40%.", "Nós reduzimos o tempo de lançamento em 40%."],
      ["He has earned the trust of the whole organization.", "Ele conquistou a confiança de toda a organização."],
      ["They have a dedicated design operations team.", "Eles têm um time dedicado de design operations."],
      ["I have always tried to put the user first.", "Eu sempre tentei colocar o usuário em primeiro lugar."],
      ["She has a natural ability to facilitate workshops.", "Ela tem uma habilidade natural para facilitar workshops."],
      ["We have had our best quarter yet.", "Nós tivemos nosso melhor trimestre até agora."],
      ["He has shown remarkable growth this year.", "Ele demonstrou um crescimento notável esse ano."],
      ["They have built something truly remarkable.", "Eles construíram algo verdadeiramente notável."],
    ],
  },
  {
    id: "was_were",
    label: "Was / Were",
    title: "Was / Were — passado do ser e estar",
    pattern: "I/He/She was — You/We/They were",
    rule: "Was → I, He, She, It. Were → You, We, They. Negativa: wasn't / weren't.",
    sentences: [
      ["I was a junior designer 5 years ago.", "Eu era designer junior há 5 anos."],
      ["She was the lead on that project.", "Ela era a líder naquele projeto."],
      ["We were a team of 4 people.", "Nós éramos uma equipe de 4 pessoas."],
      ["It was a very complex project.", "Era um projeto muito complexo."],
      ["They were great clients.", "Eles eram ótimos clientes."],
      ["I wasn't happy at that job.", "Eu não estava feliz naquele emprego."],
      ["She wasn't ready for that role.", "Ela não estava pronta para aquela função."],
      ["We weren't aligned on the deadline.", "Nós não estávamos alinhados sobre o prazo."],
      ["Was the meeting productive?", "A reunião foi produtiva?"],
      ["Were you the designer on that project?", "Você era o designer naquele projeto?"],
      ["I was responsible for the entire design.", "Eu era responsável por todo o design."],
      ["She was the only designer on the team.", "Ela era a única designer no time."],
      ["We were working under a lot of pressure.", "Nós estávamos trabalhando sob muita pressão."],
      ["It was a great opportunity to grow.", "Foi uma ótima oportunidade de crescer."],
      ["They were not easy clients to work with.", "Eles não eram clientes fáceis de trabalhar."],
      ["I wasn't confident in my English back then.", "Eu não me sentia confiante com meu inglês naquela época."],
      ["She wasn't getting enough support from management.", "Ela não estava recebendo suporte suficiente da gestão."],
      ["We weren't using a design system at the time.", "Nós não estávamos usando um design system naquela época."],
      ["Was the feedback positive?", "O feedback foi positivo?"],
      ["Were they satisfied with the final result?", "Eles ficaram satisfeitos com o resultado final?"],
      ["I was the first designer hired at that company.", "Eu fui o primeiro designer contratado naquela empresa."],
      ["She was known for her attention to detail.", "Ela era conhecida pela atenção aos detalhes."],
      ["We were ahead of schedule at first.", "No início, estávamos adiantados no cronograma."],
      ["It was a risky decision, but it paid off.", "Foi uma decisão arriscada, mas valeu a pena."],
      ["They were surprised by the user research results.", "Eles ficaram surpresos com os resultados da pesquisa."],
      ["I wasn't expecting so much responsibility.", "Eu não estava esperando tanta responsabilidade."],
      ["She wasn't involved in the early stages.", "Ela não estava envolvida nas etapas iniciais."],
      ["We weren't ready to launch, but we had to.", "Não estávamos prontos para lançar, mas tivemos que fazer."],
      ["Was the scope clearly defined?", "O escopo estava claramente definido?"],
      ["Were you part of the founding team?", "Você fazia parte do time fundador?"],
      ["I was very proud of that project.", "Eu fiquei muito orgulhoso daquele projeto."],
      ["She was promoted after that delivery.", "Ela foi promovida depois daquela entrega."],
      ["We were a remote team from day one.", "Éramos um time remoto desde o início."],
      ["It was the most challenging project of my career.", "Foi o projeto mais desafiador da minha carreira."],
      ["They were impressed with our process.", "Eles ficaram impressionados com nosso processo."],
      ["I wasn't prepared for that level of feedback.", "Eu não estava preparado para aquele nível de feedback."],
      ["She wasn't part of the decision-making process.", "Ela não fazia parte do processo de tomada de decisão."],
      ["We weren't communicating effectively.", "Nós não estávamos nos comunicando efetivamente."],
      ["Was the user journey well-documented?", "A jornada do usuário estava bem documentada?"],
      ["Were the designs approved in the first round?", "Os designs foram aprovados na primeira rodada?"],
      ["I was learning something new every week.", "Eu estava aprendendo algo novo toda semana."],
      ["She was passionate about accessibility.", "Ela era apaixonada por acessibilidade."],
      ["We were all aligned on the product vision.", "Estávamos todos alinhados na visão de produto."],
      ["It was a turning point in my career.", "Foi um ponto de virada na minha carreira."],
      ["They were open to feedback and iteration.", "Eles eram abertos a feedback e iteração."],
      ["I wasn't sure it was going to work.", "Eu não tinha certeza se ia funcionar."],
      ["She wasn't afraid to challenge the status quo.", "Ela não tinha medo de desafiar o status quo."],
      ["We weren't given enough time to do it right.", "Não nos foi dado tempo suficiente para fazer direito."],
      ["Was that the first time you led a project?", "Foi a primeira vez que você liderou um projeto?"],
      ["Were you satisfied with the outcome?", "Você ficou satisfeito com o resultado?"],
    ],
  },
  {
    id: "auxiliares",
    label: "Can / Could",
    title: "Can / Could — conseguir e pedir com educação",
    pattern: "Can = consigo | Could = poderia (mais educado)",
    rule: "Depois de can/could o verbo é sempre normal, sem -ing ou -ed. Could é mais educado que can.",
    sentences: [
      ["I can work under pressure.", "Eu consigo trabalhar sob pressão."],
      ["I can't speak English fluently yet.", "Eu ainda não consigo falar inglês fluentemente."],
      ["Can you review my design?", "Você pode revisar meu design?"],
      ["She can lead a team of 10 people.", "Ela consegue liderar uma equipe de 10 pessoas."],
      ["Could you send me the brief?", "Você poderia me mandar o briefing?"],
      ["Could we reschedule the meeting?", "Poderíamos remarcar a reunião?"],
      ["I could work on that tomorrow.", "Eu poderia trabalhar nisso amanhã."],
      ["Can we jump on a call later?", "Podemos fazer uma call mais tarde?"],
      ["I can deliver this by Friday.", "Eu consigo entregar isso até sexta."],
      ["Could you explain that again?", "Você poderia explicar isso de novo?"],
      ["I can handle multiple projects at once.", "Eu consigo lidar com vários projetos ao mesmo tempo."],
      ["She can present her work very clearly.", "Ela consegue apresentar seu trabalho com muita clareza."],
      ["Can you share your screen?", "Você pode compartilhar sua tela?"],
      ["Could you take a look at this prototype?", "Você poderia dar uma olhada nesse protótipo?"],
      ["I can't make that meeting, can we move it?", "Não consigo participar daquela reunião, podemos remarcar?"],
      ["Could you give me more context on this task?", "Você poderia me dar mais contexto sobre essa tarefa?"],
      ["I can design that component today.", "Eu consigo criar aquele componente hoje."],
      ["She can't work on that right now.", "Ela não consegue trabalhar nisso agora."],
      ["Can we align before the presentation?", "Podemos nos alinhar antes da apresentação?"],
      ["Could I get your feedback by end of day?", "Eu poderia receber seu feedback até o final do dia?"],
      ["I can learn any tool quickly.", "Eu consigo aprender qualquer ferramenta rapidamente."],
      ["She could help us with the research.", "Ela poderia nos ajudar com a pesquisa."],
      ["Can you walk me through your process?", "Você pode me explicar o seu processo?"],
      ["Could we try a different approach?", "Poderíamos tentar uma abordagem diferente?"],
      ["I can present the findings tomorrow.", "Eu consigo apresentar os resultados amanhã."],
      ["She can't attend the meeting remotely.", "Ela não consegue participar da reunião remotamente."],
      ["Can you add comments to the Figma file?", "Você pode adicionar comentários no arquivo do Figma?"],
      ["Could you share the latest version?", "Você poderia compartilhar a versão mais recente?"],
      ["I can simplify this flow significantly.", "Eu consigo simplificar bastante esse fluxo."],
      ["She could design that in a day.", "Ela poderia criar isso em um dia."],
      ["Can we get everyone on the same page?", "Podemos fazer todos ficarem alinhados?"],
      ["Could you clarify the requirements?", "Você poderia esclarecer os requisitos?"],
      ["I can't move forward without more information.", "Eu não consigo avançar sem mais informações."],
      ["She can handle that client well.", "Ela consegue lidar bem com aquele cliente."],
      ["Can you give me an example?", "Você pode me dar um exemplo?"],
      ["Could we set up a quick sync?", "Poderíamos marcar uma sincronização rápida?"],
      ["I can create a prototype for user testing.", "Eu consigo criar um protótipo para testes com usuários."],
      ["She could contribute a lot to that project.", "Ela poderia contribuir muito para aquele projeto."],
      ["Can you check the accessibility of this screen?", "Você pode verificar a acessibilidade dessa tela?"],
      ["Could you help me structure this presentation?", "Você poderia me ajudar a estruturar essa apresentação?"],
      ["I can work with any type of team.", "Eu consigo trabalhar com qualquer tipo de time."],
      ["She can't approve changes without the client's sign-off.", "Ela não pode aprovar mudanças sem o aval do cliente."],
      ["Can we do a design critique session?", "Podemos fazer uma sessão de crítica de design?"],
      ["Could you send me the design tokens?", "Você poderia me enviar os design tokens?"],
      ["I can help onboard the new designer.", "Eu consigo ajudar no onboarding do novo designer."],
      ["She could lead the workshop if needed.", "Ela poderia liderar o workshop se necessário."],
      ["Can you make it more accessible?", "Você pode tornar isso mais acessível?"],
      ["Could you review the copy as well?", "Você poderia revisar o texto também?"],
      ["I can't commit to that deadline.", "Eu não consigo me comprometer com aquele prazo."],
      ["She can clearly articulate design decisions.", "Ela consegue articular claramente as decisões de design."],
    ],
  },
  {
    id: "should_must",
    label: "Should / Must",
    title: "Should / Must — conselho e obrigação",
    pattern: "Should = deveria | Must = precisa/obrigado",
    rule: "Should → conselho. Must → obrigação forte. Ambos seguidos de verbo normal, sem to.",
    sentences: [
      ["You should improve your English.", "Você deveria melhorar seu inglês."],
      ["I should update my portfolio.", "Eu deveria atualizar meu portfólio."],
      ["She should ask for feedback.", "Ela deveria pedir feedback."],
      ["You shouldn't give up so easily.", "Você não deveria desistir tão fácil."],
      ["I must finish this by Friday.", "Eu preciso terminar isso até sexta."],
      ["We must meet the deadline.", "Nós precisamos cumprir o prazo."],
      ["You must not share this file.", "Você não pode compartilhar esse arquivo."],
      ["I should learn more about accessibility.", "Eu deveria aprender mais sobre acessibilidade."],
      ["Should I send the file now?", "Eu deveria mandar o arquivo agora?"],
      ["He must improve his communication skills.", "Ele precisa melhorar suas habilidades de comunicação."],
      ["You should document your design decisions.", "Você deveria documentar suas decisões de design."],
      ["I should speak up more in meetings.", "Eu deveria me manifestar mais nas reuniões."],
      ["She should set clearer boundaries.", "Ela deveria definir limites mais claros."],
      ["We shouldn't launch without testing.", "Nós não deveríamos lançar sem testar."],
      ["I must deliver quality work every time.", "Eu preciso entregar trabalho de qualidade toda vez."],
      ["We must involve users in the process.", "Nós precisamos envolver os usuários no processo."],
      ["You must not ignore accessibility.", "Você não pode ignorar acessibilidade."],
      ["I should build a stronger network.", "Eu deveria construir uma rede profissional mais forte."],
      ["Should we validate this idea first?", "Deveríamos validar essa ideia primeiro?"],
      ["She must lead by example.", "Ela precisa liderar pelo exemplo."],
      ["You should start with the user's needs.", "Você deveria começar pelas necessidades do usuário."],
      ["I should be more strategic in my thinking.", "Eu deveria ser mais estratégico no meu raciocínio."],
      ["He should take ownership of his decisions.", "Ele deveria assumir a responsabilidade pelas suas decisões."],
      ["We shouldn't rush the design process.", "Nós não deveríamos apressar o processo de design."],
      ["I must review this before sharing.", "Eu preciso revisar isso antes de compartilhar."],
      ["We must align with stakeholders first.", "Nós precisamos nos alinhar com os stakeholders primeiro."],
      ["You must not change the scope without approval.", "Você não pode mudar o escopo sem aprovação."],
      ["I should ask for help when I'm stuck.", "Eu deveria pedir ajuda quando estou travado."],
      ["Should I include the developer in this meeting?", "Eu deveria incluir o desenvolvedor nessa reunião?"],
      ["He must understand the business goals.", "Ele precisa entender os objetivos de negócio."],
      ["You should present your rationale, not just the design.", "Você deveria apresentar sua justificativa, não apenas o design."],
      ["I should invest more time in user research.", "Eu deveria investir mais tempo em pesquisa com usuários."],
      ["She should challenge assumptions early.", "Ela deveria questionar as premissas cedo."],
      ["We shouldn't ignore negative user feedback.", "Nós não deveríamos ignorar feedback negativo dos usuários."],
      ["I must keep my skills up to date.", "Eu preciso manter minhas habilidades atualizadas."],
      ["We must test on real devices.", "Nós precisamos testar em dispositivos reais."],
      ["You must not make assumptions without data.", "Você não pode fazer suposições sem dados."],
      ["I should take breaks to stay creative.", "Eu deveria fazer pausas para continuar criativo."],
      ["Should we run another round of testing?", "Deveríamos fazer outra rodada de testes?"],
      ["She must be more transparent with the team.", "Ela precisa ser mais transparente com o time."],
      ["You should listen more before jumping to solutions.", "Você deveria ouvir mais antes de ir direto para soluções."],
      ["I should acknowledge my mistakes and move on.", "Eu deveria reconhecer meus erros e seguir em frente."],
      ["He should communicate blockers early.", "Ele deveria comunicar os impedimentos cedo."],
      ["We shouldn't ship a feature we haven't validated.", "Nós não deveríamos lançar uma funcionalidade que não validamos."],
      ["I must be consistent with the design language.", "Eu preciso ser consistente com a linguagem de design."],
      ["We must present data to support our decisions.", "Nós precisamos apresentar dados para embasar nossas decisões."],
      ["You must not underestimate the importance of copy.", "Você não pode subestimar a importância do texto."],
      ["I should set better priorities this week.", "Eu deveria definir melhores prioridades essa semana."],
      ["Should we involve the marketing team earlier?", "Deveríamos envolver o time de marketing mais cedo?"],
      ["She must take this opportunity seriously.", "Ela precisa levar essa oportunidade a sério."],
    ],
  },
  {
    id: "wh",
    label: "WH Questions",
    title: "WH Questions — perguntas abertas",
    pattern: "[WH] + do/did/will + sujeito + verbo?",
    rule: "What, Where, When, Who, Why, How. No passado usa did. No presente usa do/does. Com auxiliares inverte a ordem.",
    sentences: [
      ["What do you do for a living?", "O que você faz para viver?"],
      ["Where do you work?", "Onde você trabalha?"],
      ["When did you start your career?", "Quando você começou sua carreira?"],
      ["Why did you leave your last job?", "Por que você saiu do último emprego?"],
      ["How do you manage your projects?", "Como você gerencia seus projetos?"],
      ["Who did you work with on that project?", "Com quem você trabalhou naquele projeto?"],
      ["What will you do next year?", "O que você vai fazer no ano que vem?"],
      ["Where did you learn design?", "Onde você aprendeu design?"],
      ["How long did you work there?", "Por quanto tempo você trabalhou lá?"],
      ["Why should I hire you?", "Por que eu deveria te contratar?"],
      ["What are you working on right now?", "Em que você está trabalhando agora?"],
      ["Where do you see yourself in 5 years?", "Onde você se vê em 5 anos?"],
      ["When will you finish the prototype?", "Quando você vai terminar o protótipo?"],
      ["Why did you choose design as a career?", "Por que você escolheu design como carreira?"],
      ["How do you handle feedback?", "Como você lida com feedback?"],
      ["Who is responsible for the design system?", "Quem é responsável pelo design system?"],
      ["What tools do you use for prototyping?", "Quais ferramentas você usa para prototipar?"],
      ["Where did you get that insight?", "Onde você obteve esse insight?"],
      ["When did you start using Figma?", "Quando você começou a usar o Figma?"],
      ["Why is accessibility important in design?", "Por que acessibilidade é importante no design?"],
      ["How do you prioritize your tasks?", "Como você prioriza suas tarefas?"],
      ["Who gave you the most valuable feedback?", "Quem te deu o feedback mais valioso?"],
      ["What was the biggest challenge in that project?", "Qual foi o maior desafio naquele projeto?"],
      ["Where do you find design inspiration?", "Onde você encontra inspiração para design?"],
      ["When should we involve the users?", "Quando devemos envolver os usuários?"],
      ["Why did the project fail?", "Por que o projeto falhou?"],
      ["How did you solve that usability problem?", "Como você resolveu aquele problema de usabilidade?"],
      ["Who approved the final design?", "Quem aprovou o design final?"],
      ["What is your design process?", "Qual é o seu processo de design?"],
      ["Where do you want to grow professionally?", "Onde você quer crescer profissionalmente?"],
      ["When are you available for a call?", "Quando você está disponível para uma call?"],
      ["Why did you decide to redesign that flow?", "Por que você decidiu redesenhar aquele fluxo?"],
      ["How do you collaborate with developers?", "Como você colabora com os desenvolvedores?"],
      ["Who is the target user for this product?", "Quem é o usuário alvo desse produto?"],
      ["What metrics do you use to measure success?", "Quais métricas você usa para medir o sucesso?"],
      ["Where do you draw the line between UX and UI?", "Onde você traça a linha entre UX e UI?"],
      ["When did you realize design was your passion?", "Quando você percebeu que design era sua paixão?"],
      ["Why did you pivot the design mid-project?", "Por que você mudou o design no meio do projeto?"],
      ["How do you stay updated on design trends?", "Como você se mantém atualizado sobre tendências de design?"],
      ["Who mentored you early in your career?", "Quem foi seu mentor no início da sua carreira?"],
      ["What would you do differently next time?", "O que você faria diferente na próxima vez?"],
      ["Where do you struggle the most as a designer?", "Onde você tem mais dificuldade como designer?"],
      ["When do you know a design is done?", "Quando você sabe que um design está pronto?"],
      ["Why is user research essential before designing?", "Por que a pesquisa com usuários é essencial antes de projetar?"],
      ["How do you present your work to non-designers?", "Como você apresenta seu trabalho para não-designers?"],
      ["Who are the main stakeholders in your projects?", "Quem são os principais stakeholders nos seus projetos?"],
      ["What is the hardest part of being a designer?", "Qual é a parte mais difícil de ser designer?"],
      ["Where do you think design is heading?", "Para onde você acha que o design está indo?"],
      ["When do you ask for feedback during the process?", "Quando você pede feedback durante o processo?"],
      ["Why do you think design thinking matters?", "Por que você acha que o design thinking importa?"],
    ],
  },
  {
    id: "comparacao",
    label: "Comparações",
    title: "Comparações — mais que, melhor que",
    pattern: "[A] is more [adj] than [B] / [adj]-er than",
    rule: "Palavras curtas: adiciona -er (bigger, faster). Palavras longas: usa more (more complex, more expensive). Irregulares: good → better, bad → worse.",
    sentences: [
      ["This project is more complex than the last one.", "Este projeto é mais complexo que o último."],
      ["My English is better than it was last year.", "Meu inglês está melhor do que estava ano passado."],
      ["This tool is more expensive than Figma.", "Essa ferramenta é mais cara que o Figma."],
      ["Working remotely is easier than commuting.", "Trabalhar remotamente é mais fácil que se deslocar."],
      ["This client is bigger than the previous one.", "Esse cliente é maior que o anterior."],
      ["Design is more important than people think.", "Design é mais importante do que as pessoas pensam."],
      ["My new job is better than the old one.", "Meu novo emprego é melhor que o anterior."],
      ["This deadline is tighter than usual.", "Esse prazo é mais apertado que o normal."],
      ["This version is cleaner than the first draft.", "Essa versão está mais limpa que o primeiro rascunho."],
      ["Communication is harder than design sometimes.", "Comunicação é mais difícil que design às vezes."],
      ["This prototype is more interactive than the last one.", "Esse protótipo é mais interativo que o último."],
      ["The new onboarding is shorter and clearer.", "O novo onboarding é mais curto e mais claro."],
      ["This design system is more scalable than before.", "Esse design system é mais escalável do que antes."],
      ["User research is more valuable than assumptions.", "Pesquisa com usuários é mais valiosa do que suposições."],
      ["The mobile version is harder to design than desktop.", "A versão mobile é mais difícil de projetar do que a desktop."],
      ["My portfolio is stronger than it was two years ago.", "Meu portfólio está mais forte do que estava há dois anos."],
      ["This feedback was more useful than the last round.", "Esse feedback foi mais útil do que a rodada anterior."],
      ["The new layout is simpler and more intuitive.", "O novo layout é mais simples e mais intuitivo."],
      ["Writing is more challenging than drawing.", "Escrever é mais desafiador do que desenhar."],
      ["This sprint was more productive than the previous one.", "Esse sprint foi mais produtivo que o anterior."],
      ["The team is more aligned now than before.", "O time está mais alinhado agora do que antes."],
      ["This client is easier to work with than the last.", "Esse cliente é mais fácil de trabalhar do que o último."],
      ["Good design is cheaper than bad design in the long run.", "Bom design é mais barato que mau design a longo prazo."],
      ["This flow is shorter and less confusing.", "Esse fluxo é mais curto e menos confuso."],
      ["The new version is much better than the beta.", "A nova versão é muito melhor do que a versão beta."],
      ["Working in a team is more rewarding than working alone.", "Trabalhar em equipe é mais gratificante do que trabalhar sozinho."],
      ["This role is more senior than my last position.", "Esse cargo é mais sênior do que minha posição anterior."],
      ["The interface is more accessible than before.", "A interface está mais acessível do que antes."],
      ["This approach is safer than the original one.", "Essa abordagem é mais segura do que a original."],
      ["The new hire is more experienced than we expected.", "A nova contratação é mais experiente do que esperávamos."],
      ["Data-driven decisions are better than gut feelings.", "Decisões baseadas em dados são melhores do que intuição."],
      ["This icon is clearer than the previous one.", "Esse ícone é mais claro do que o anterior."],
      ["The design review process is more structured now.", "O processo de revisão de design está mais estruturado agora."],
      ["This problem is more interesting than it looks.", "Esse problema é mais interessante do que parece."],
      ["The new color palette is more consistent.", "A nova paleta de cores é mais consistente."],
      ["User interviews are more insightful than surveys.", "Entrevistas com usuários são mais esclarecedoras do que pesquisas."],
      ["This component is more reusable than the old one.", "Esse componente é mais reutilizável do que o antigo."],
      ["Remote work is more flexible but harder to collaborate.", "Trabalho remoto é mais flexível, mas mais difícil de colaborar."],
      ["This case study is more compelling than the last.", "Esse case study é mais convincente que o último."],
      ["The product is more intuitive than competitors' versions.", "O produto é mais intuitivo do que as versões dos concorrentes."],
      ["The revised brief is clearer than the original.", "O briefing revisado é mais claro que o original."],
      ["This workshop was more engaging than the last.", "Esse workshop foi mais envolvente que o último."],
      ["Senior designers think more strategically than juniors.", "Designers sêniores pensam de forma mais estratégica que os juniores."],
      ["This version is closer to what users actually need.", "Essa versão está mais próxima do que os usuários realmente precisam."],
      ["Cross-functional work is harder but more impactful.", "Trabalho multifuncional é mais difícil, mas mais impactante."],
      ["This market is more competitive than last year.", "Esse mercado está mais competitivo do que no ano passado."],
      ["The updated design is more polished than the draft.", "O design atualizado está mais refinado do que o rascunho."],
      ["This project required more research than expected.", "Esse projeto exigiu mais pesquisa do que o esperado."],
      ["The second iteration is always better than the first.", "A segunda iteração é sempre melhor que a primeira."],
      ["Good communication is just as important as good design.", "Boa comunicação é tão importante quanto bom design."],
    ],
  },
  {
    id: "a_the",
    label: "A / The",
    title: "A / The — artigos",
    pattern: "a = qualquer um | the = específico",
    rule: "A/An → qualquer um, primeira menção. The → específico ou já mencionado. An → antes de som de vogal (an idea, an hour). Profissões: I am a designer.",
    sentences: [
      ["I work at a tech company.", "Eu trabalho em uma empresa de tecnologia."],
      ["The company has 200 employees.", "A empresa tem 200 funcionários."],
      ["I had a meeting this morning.", "Eu tive uma reunião essa manhã."],
      ["The meeting was very productive.", "A reunião foi muito produtiva."],
      ["I am a product designer.", "Eu sou product designer."],
      ["She had an idea for the project.", "Ela teve uma ideia para o projeto."],
      ["The idea was approved by the client.", "A ideia foi aprovada pelo cliente."],
      ["I sent a file to the team.", "Eu mandei um arquivo para o time."],
      ["The file needs to be updated.", "O arquivo precisa ser atualizado."],
      ["We have a new client this month.", "Nós temos um novo cliente esse mês."],
      ["I found a bug in the prototype.", "Eu encontrei um bug no protótipo."],
      ["The bug was fixed by the developer.", "O bug foi corrigido pelo desenvolvedor."],
      ["She is a UX researcher.", "Ela é UX researcher."],
      ["The researcher ran three user interviews.", "A pesquisadora conduziu três entrevistas com usuários."],
      ["I need a solution for this problem.", "Eu preciso de uma solução para esse problema."],
      ["The solution was simpler than expected.", "A solução foi mais simples do que o esperado."],
      ["We hired a new designer last week.", "Nós contratamos um novo designer semana passada."],
      ["The designer joined the team on Monday.", "O designer entrou no time na segunda-feira."],
      ["I wrote a brief for the project.", "Eu escrevi um briefing para o projeto."],
      ["The brief was approved by the manager.", "O briefing foi aprovado pelo gestor."],
      ["She built a component library for the team.", "Ela construiu uma biblioteca de componentes para o time."],
      ["The library is used across all products.", "A biblioteca é usada em todos os produtos."],
      ["I gave a presentation at the conference.", "Eu dei uma apresentação na conferência."],
      ["The presentation went very well.", "A apresentação foi muito bem."],
      ["We launched a new feature last week.", "Nós lançamos uma nova funcionalidade semana passada."],
      ["The feature was loved by users.", "A funcionalidade foi adorada pelos usuários."],
      ["I created a prototype for testing.", "Eu criei um protótipo para testes."],
      ["The prototype helped us validate the idea.", "O protótipo nos ajudou a validar a ideia."],
      ["She wrote an article about UX design.", "Ela escreveu um artigo sobre UX design."],
      ["The article was shared hundreds of times.", "O artigo foi compartilhado centenas de vezes."],
      ["I had an interview for a senior role.", "Eu tive uma entrevista para um cargo sênior."],
      ["The interview lasted two hours.", "A entrevista durou duas horas."],
      ["We proposed a new design direction.", "Nós propusemos uma nova direção de design."],
      ["The direction was well-received by the team.", "A direção foi bem recebida pelo time."],
      ["I joined a design community online.", "Eu entrei em uma comunidade de design online."],
      ["The community helped me grow a lot.", "A comunidade me ajudou a crescer muito."],
      ["She shared an update in the meeting.", "Ela compartilhou uma atualização na reunião."],
      ["The update surprised everyone.", "A atualização surpreendeu a todos."],
      ["I found an error in the design spec.", "Eu encontrei um erro na especificação de design."],
      ["The error was corrected before the handoff.", "O erro foi corrigido antes do handoff."],
      ["We built a dashboard for tracking metrics.", "Nós construímos um dashboard para acompanhar métricas."],
      ["The dashboard helped the team make faster decisions.", "O dashboard ajudou o time a tomar decisões mais rápidas."],
      ["I attended a workshop on design systems.", "Eu participei de um workshop sobre design systems."],
      ["The workshop changed the way I approach design.", "O workshop mudou a forma como eu abordo o design."],
      ["She sent a proposal to the client.", "Ela enviou uma proposta para o cliente."],
      ["The proposal was accepted.", "A proposta foi aceita."],
      ["I discovered an issue during the review.", "Eu descobri um problema durante a revisão."],
      ["The issue was resolved the same day.", "O problema foi resolvido no mesmo dia."],
      ["We had an unexpected change in scope.", "Nós tivemos uma mudança inesperada de escopo."],
      ["The change affected our timeline significantly.", "A mudança afetou significativamente nosso cronograma."],
    ],
  },
  {
    id: "in_on_at",
    label: "In / On / At",
    title: "In / On / At — preposições de lugar e tempo",
    pattern: "at = ponto | in = dentro | on = projeto/dia",
    rule: "At → empresa, horário (at work, at 3pm). In → país, cidade, ano (in Brazil, in 2020). On → projeto, dia da semana (on a project, on Monday). From → origem (work from home).",
    sentences: [
      ["I work at a startup.", "Eu trabalho em uma startup."],
      ["I live in Brazil.", "Eu moro no Brasil."],
      ["I am working on a new project.", "Eu estou trabalhando em um projeto novo."],
      ["The meeting is at 3pm.", "A reunião é às 15h."],
      ["I work from home on Fridays.", "Eu trabalho de casa nas sextas."],
      ["I was born in São Paulo.", "Eu nasci em São Paulo."],
      ["We met on Monday.", "Nós nos encontramos na segunda-feira."],
      ["She is at the office today.", "Ela está no escritório hoje."],
      ["I started working on this in 2020.", "Eu comecei a trabalhar nisso em 2020."],
      ["I will be at the conference next week.", "Eu estarei na conferência semana que vem."],
      ["I studied design in college.", "Eu estudei design na faculdade."],
      ["She works at a large agency.", "Ela trabalha em uma grande agência."],
      ["We are working on a tight deadline.", "Estamos trabalhando em um prazo apertado."],
      ["The presentation is at 10am.", "A apresentação é às 10h."],
      ["I worked from home during the pandemic.", "Eu trabalhei de casa durante a pandemia."],
      ["He grew up in Rio de Janeiro.", "Ele cresceu no Rio de Janeiro."],
      ["We are meeting on Thursday.", "Nós nos reunimos na quinta-feira."],
      ["She is at a client meeting right now.", "Ela está em uma reunião com o cliente agora."],
      ["I joined this company in 2021.", "Eu entrei nessa empresa em 2021."],
      ["I will present my ideas at the workshop.", "Eu vou apresentar minhas ideias no workshop."],
      ["He graduated in design at USP.", "Ele se formou em design na USP."],
      ["She is working at a product company.", "Ela está trabalhando em uma empresa de produto."],
      ["I am working on the design system right now.", "Eu estou trabalhando no design system agora."],
      ["The standup is at 9am every day.", "O standup é às 9h todos os dias."],
      ["I worked from home three days a week.", "Eu trabalhava de casa três dias por semana."],
      ["She was born in 1990 in Campinas.", "Ela nasceu em 1990 em Campinas."],
      ["We have a design review on Wednesday.", "Nós temos uma revisão de design na quarta."],
      ["He is at his best when working on complex problems.", "Ele está no seu melhor quando trabalha em problemas complexos."],
      ["I started freelancing in 2018.", "Eu comecei a trabalhar como freelancer em 2018."],
      ["I will see you at the event.", "Eu vou te ver no evento."],
      ["She studied at FAAP.", "Ela estudou na FAAP."],
      ["I am working on an important case study.", "Eu estou trabalhando em um case study importante."],
      ["The deadline is at midnight.", "O prazo é à meia-noite."],
      ["I prefer working from home in the mornings.", "Eu prefiro trabalhar de casa de manhã."],
      ["He started his career in an agency.", "Ele começou sua carreira em uma agência."],
      ["We are aligning on Friday.", "Nós nos alinhamos na sexta."],
      ["She is at the top of her career.", "Ela está no auge da sua carreira."],
      ["I worked on this design in December.", "Eu trabalhei nesse design em dezembro."],
      ["I will be at the office at 8am.", "Eu estarei no escritório às 8h."],
      ["He studied typography in depth.", "Ele estudou tipografia em profundidade."],
      ["We are working at full capacity.", "Estamos trabalhando em capacidade total."],
      ["I collaborated on this project with a friend.", "Eu colaborei nesse projeto com um amigo."],
      ["The launch is scheduled for next month.", "O lançamento está marcado para o mês que vem."],
      ["She arrived at the meeting on time.", "Ela chegou à reunião no horário."],
      ["I learned design thinking in a course.", "Eu aprendi design thinking em um curso."],
      ["He started working at the company in January.", "Ele começou a trabalhar na empresa em janeiro."],
      ["We are meeting on the last day of the sprint.", "Nós nos reunimos no último dia do sprint."],
      ["She presented at the all-hands meeting.", "Ela apresentou na reunião geral."],
      ["I started the project in March.", "Eu comecei o projeto em março."],
      ["I will pitch my idea at the next team meeting.", "Eu vou apresentar minha ideia na próxima reunião do time."],
    ],
  },
  {
    id: "for_since",
    label: "For / Since",
    title: "For / Since — duração de tempo",
    pattern: "for = duração | since = desde quando",
    rule: "For → quanto tempo durou (for 8 years, for 3 months). Since → quando começou (since 2016, since January).",
    sentences: [
      ["I have worked in design for 8 years.", "Eu trabalho em design há 8 anos."],
      ["I have lived in Sumaré since 2019.", "Eu moro em Sumaré desde 2019."],
      ["She has been a designer for 5 years.", "Ela é designer há 5 anos."],
      ["We have been partners since 2021.", "Nós somos parceiros desde 2021."],
      ["I have been studying English for 3 months.", "Eu estudo inglês há 3 meses."],
      ["He has worked there since he graduated.", "Ele trabalha lá desde que se formou."],
      ["I haven't changed jobs for 4 years.", "Eu não troco de emprego há 4 anos."],
      ["We have used Figma since 2018.", "Nós usamos Figma desde 2018."],
      ["She has been the manager for 2 years.", "Ela é gerente há 2 anos."],
      ["I have known him since we worked together.", "Eu o conheço desde quando trabalhamos juntos."],
      ["I have been freelancing for six months.", "Eu trabalho como freelancer há seis meses."],
      ["She has been leading the team since March.", "Ela lidera o time desde março."],
      ["We have been working on this feature for a week.", "Nós estamos trabalhando nessa funcionalidade há uma semana."],
      ["He has been learning UX since 2022.", "Ele aprende UX desde 2022."],
      ["I have been at this company for three years.", "Eu estou nessa empresa há três anos."],
      ["She has been working remotely since the pandemic.", "Ela trabalha remotamente desde a pandemia."],
      ["We have been iterating on this design for two sprints.", "Nós iteramos nesse design por dois sprints."],
      ["He has been waiting for feedback for a week.", "Ele está esperando feedback há uma semana."],
      ["I have been practicing English since January.", "Eu pratico inglês desde janeiro."],
      ["She has been mentoring designers for over a year.", "Ela faz a mentoria de designers há mais de um ano."],
      ["I have been using this tool for about a year.", "Eu uso essa ferramenta há cerca de um ano."],
      ["He has been growing a lot since he joined.", "Ele tem crescido muito desde que entrou."],
      ["We have been running sprints for two years.", "Nós conduzimos sprints há dois anos."],
      ["She has been improving her portfolio since last year.", "Ela melhora seu portfólio desde o ano passado."],
      ["I have been in this industry for over a decade.", "Eu estou nessa indústria há mais de uma década."],
      ["He has been managing remote teams for 3 years.", "Ele gerencia times remotos há 3 anos."],
      ["We have been planning this launch for months.", "Nós planejamos esse lançamento por meses."],
      ["She has been working for this client since 2020.", "Ela trabalha para esse cliente desde 2020."],
      ["I have been pushing myself to grow since my last job.", "Eu me desafio a crescer desde meu último emprego."],
      ["He has been contributing to open-source for years.", "Ele contribui para projetos open-source há anos."],
      ["We have been using this design system since it launched.", "Nós usamos esse design system desde que foi lançado."],
      ["She has been passionate about typography for a long time.", "Ela é apaixonada por tipografia há muito tempo."],
      ["I have been working on my communication skills for months.", "Eu trabalho minhas habilidades de comunicação há meses."],
      ["He has been with the company since the beginning.", "Ele está na empresa desde o início."],
      ["We have been growing our team for the past year.", "Nós crescemos nosso time no último ano."],
      ["She has been running workshops for three years.", "Ela conduz workshops há três anos."],
      ["I have been taking notes in every meeting since 2021.", "Eu faço anotações em cada reunião desde 2021."],
      ["He has been improving his English for six months.", "Ele melhora seu inglês há seis meses."],
      ["We have been iterating on the onboarding since the beta.", "Nós iteramos no onboarding desde a versão beta."],
      ["She has been working at that startup for two years.", "Ela trabalha naquela startup há dois anos."],
      ["I haven't taken a vacation for over a year.", "Eu não tiro férias há mais de um ano."],
      ["He has been recognized as a top performer since Q2.", "Ele é reconhecido como top performer desde o segundo trimestre."],
      ["We have been scaling the product since last quarter.", "Nós escalamos o produto desde o trimestre passado."],
      ["She has been exploring motion design for a few months.", "Ela explora motion design há alguns meses."],
      ["I have been getting better at presenting for a year.", "Eu melhoro em apresentar há um ano."],
      ["He has been building side projects since 2020.", "Ele constrói projetos paralelos desde 2020."],
      ["We have been working with this agency for six months.", "Nós trabalhamos com essa agência há seis meses."],
      ["She has been leading product design since she was promoted.", "Ela lidera o product design desde que foi promovida."],
      ["I have been documenting my process for better case studies.", "Eu documento meu processo para melhores case studies."],
      ["He has been at the top of his game for years.", "Ele está no melhor da sua forma há anos."],
    ],
  },
  {
    id: "have_exp",
    label: "Have + experiência",
    title: "Have + verbo no passado — experiência acumulada",
    pattern: "I have [verb-ed]...",
    rule: "Usado para falar de algo que aconteceu no passado e ainda tem impacto hoje. I have worked = eu já trabalhei / eu trabalho há X tempo.",
    sentences: [
      ["I have worked in design for 8 years.", "Eu trabalho em design há 8 anos."],
      ["I have built several design systems.", "Eu já construí vários design systems."],
      ["I have worked with international clients.", "Eu já trabalhei com clientes internacionais."],
      ["I have led teams of up to 10 people.", "Eu já liderei equipes de até 10 pessoas."],
      ["I have used Figma, Sketch, and Adobe XD.", "Eu já usei Figma, Sketch e Adobe XD."],
      ["I have worked in startups and big companies.", "Eu já trabalhei em startups e grandes empresas."],
      ["I have improved a lot this year.", "Eu melhorei muito esse ano."],
      ["I have learned a lot from my mistakes.", "Eu aprendi muito com meus erros."],
      ["I have never worked outside Brazil.", "Eu nunca trabalhei fora do Brasil."],
      ["I have always been passionate about design.", "Eu sempre fui apaixonado por design."],
      ["I have shipped over 30 product features.", "Eu já lancei mais de 30 funcionalidades de produto."],
      ["I have run dozens of usability tests.", "Eu já conduzi dezenas de testes de usabilidade."],
      ["I have mentored junior designers throughout my career.", "Eu já orientei designers juniores durante toda minha carreira."],
      ["I have presented my work to executives.", "Eu já apresentei meu trabalho para executivos."],
      ["I have collaborated with engineers, PMs, and marketers.", "Eu já colaborei com engenheiros, PMs e profissionais de marketing."],
      ["I have redesigned products from the ground up.", "Eu já redesenhei produtos do zero."],
      ["I have delivered projects under tight deadlines.", "Eu já entreguei projetos com prazos apertados."],
      ["I have worked on mobile, web, and desktop products.", "Eu já trabalhei em produtos mobile, web e desktop."],
      ["I have contributed to both B2B and B2C products.", "Eu já contribuí para produtos B2B e B2C."],
      ["I have spoken at two design meetups.", "Eu já falei em dois meetups de design."],
      ["I have created brand identities from scratch.", "Eu já criei identidades de marca do zero."],
      ["I have conducted over 50 user interviews.", "Eu já conduzi mais de 50 entrevistas com usuários."],
      ["I have published case studies on my portfolio.", "Eu já publiquei case studies no meu portfólio."],
      ["I have managed design projects end to end.", "Eu já gerenciei projetos de design de ponta a ponta."],
      ["I have worked on products with millions of users.", "Eu já trabalhei em produtos com milhões de usuários."],
      ["I have contributed to accessibility improvements.", "Eu já contribuí para melhorias de acessibilidade."],
      ["I have implemented design thinking in teams.", "Eu já implementei design thinking em times."],
      ["I have used research to drive product decisions.", "Eu já usei pesquisa para direcionar decisões de produto."],
      ["I have worked in agile and waterfall environments.", "Eu já trabalhei em ambientes ágeis e waterfall."],
      ["I have helped teams improve their design processes.", "Eu já ajudei times a melhorar seus processos de design."],
      ["I have increased user satisfaction through redesigns.", "Eu já aumentei a satisfação dos usuários por meio de redesigns."],
      ["I have worked with C-level stakeholders.", "Eu já trabalhei com stakeholders de nível C."],
      ["I have grown from a junior to a senior designer.", "Eu cresci de designer júnior a sênior."],
      ["I have documented entire design systems.", "Eu já documentei design systems completos."],
      ["I have aligned cross-functional teams on design direction.", "Eu já alinhei times multifuncionais em direções de design."],
      ["I have introduced UX practices to non-design teams.", "Eu já introduzi práticas de UX em times não-designers."],
      ["I have reduced drop-off rates through UX improvements.", "Eu já reduzi taxas de abandono por meio de melhorias de UX."],
      ["I have designed for accessibility and inclusion.", "Eu já projetei para acessibilidade e inclusão."],
      ["I have pushed for user research in every project.", "Eu sempre defendi pesquisa com usuários em cada projeto."],
      ["I have earned the trust of clients and stakeholders.", "Eu já conquistei a confiança de clientes e stakeholders."],
      ["I have made difficult design decisions under pressure.", "Eu já tomei decisões difíceis de design sob pressão."],
      ["I have adapted to fast-changing product environments.", "Eu já me adaptei a ambientes de produto em rápida mudança."],
      ["I have balanced speed and quality effectively.", "Eu já equilibrei velocidade e qualidade de forma eficaz."],
      ["I have built lasting professional relationships.", "Eu já construí relacionamentos profissionais duradouros."],
      ["I have contributed to products that millions use daily.", "Eu já contribuí para produtos que milhões usam diariamente."],
      ["I have solved problems that directly impacted business results.", "Eu já resolvi problemas que impactaram diretamente os resultados do negócio."],
      ["I have worked through ambiguity and delivered clarity.", "Eu já trabalhei em meio à ambiguidade e entreguei clareza."],
      ["I have grown more confident presenting in English.", "Eu me tornei mais confiante em apresentar em inglês."],
      ["I have used data and empathy to create better products.", "Eu já usei dados e empatia para criar produtos melhores."],
      ["I have become a designer who leads with purpose.", "Eu me tornei um designer que lidera com propósito."],
    ],
  },
  {
    id: "phrasal",
    label: "Phrasal verbs",
    title: "Phrasal verbs — os mais usados no trabalho",
    pattern: "verbo + preposição = novo significado",
    rule: "A preposição muda tudo: give up = desistir, give in = ceder. look for = procurar, look up = pesquisar. set up = configurar, show up = aparecer.",
    sentences: [
      ["I gave up that project because it was toxic.", "Eu desisti daquele projeto porque era tóxico."],
      ["I'm looking for a new opportunity.", "Estou procurando uma nova oportunidade."],
      ["Can you set up the meeting for Thursday?", "Você pode marcar a reunião para quinta?"],
      ["He didn't show up to the presentation.", "Ele não apareceu para a apresentação."],
      ["I found out the problem was in the brief.", "Eu descobri que o problema estava no briefing."],
      ["Let's go on with the project.", "Vamos continuar com o projeto."],
      ["I need to log in to the platform.", "Eu preciso entrar na plataforma."],
      ["Please sign up before the event.", "Por favor, se cadastre antes do evento."],
      ["I need to look up the client's name.", "Eu preciso pesquisar o nome do cliente."],
      ["She turned down the job offer.", "Ela recusou a oferta de emprego."],
      ["I need to catch up on the project status.", "Eu preciso me atualizar sobre o status do projeto."],
      ["Let's wrap up the meeting.", "Vamos encerrar a reunião."],
      ["Can you follow up with the client?", "Você pode fazer um follow-up com o cliente?"],
      ["I'll reach out to the team tomorrow.", "Eu vou entrar em contato com o time amanhã."],
      ["We need to move on from this approach.", "Precisamos seguir em frente com uma abordagem diferente."],
      ["Can you take over while I'm away?", "Você pode assumir enquanto eu estiver fora?"],
      ["Let's kick off the new sprint.", "Vamos dar início ao novo sprint."],
      ["I had to cut down the scope.", "Eu tive que reduzir o escopo."],
      ["She brought up a great point in the meeting.", "Ela levantou um ótimo ponto na reunião."],
      ["We need to figure out the root cause.", "Precisamos descobrir a causa raiz."],
      ["I'll put together a proposal.", "Eu vou montar uma proposta."],
      ["He backed out of the deal at the last minute.", "Ele desistiu do acordo na última hora."],
      ["Can you pull up the latest version?", "Você pode abrir a versão mais recente?"],
      ["Let's break down the problem.", "Vamos decompor o problema."],
      ["I need to check in with the developer.", "Eu preciso conversar rapidamente com o desenvolvedor."],
      ["We ran out of time during the workshop.", "Ficamos sem tempo durante o workshop."],
      ["She stepped up when the lead designer left.", "Ela assumiu quando o designer líder saiu."],
      ["I'll hand off the files by end of day.", "Eu vou fazer o handoff dos arquivos até o final do dia."],
      ["Can you zoom in on that section?", "Você pode dar um zoom naquela seção?"],
      ["Let's sync up before the presentation.", "Vamos nos sincronizar antes da apresentação."],
      ["I'll bring up the issue in the next meeting.", "Eu vou levantar o problema na próxima reunião."],
      ["Can you help me sort out this issue?", "Você pode me ajudar a resolver esse problema?"],
      ["He took on too many projects at once.", "Ele assumiu muitos projetos de uma vez."],
      ["We need to narrow down the options.", "Precisamos reduzir as opções."],
      ["She pointed out a critical usability issue.", "Ela apontou um problema crítico de usabilidade."],
      ["Let's go over the feedback together.", "Vamos revisar o feedback juntos."],
      ["I'll sum up the key decisions.", "Eu vou resumir as decisões-chave."],
      ["He put off the design review until next week.", "Ele adiou a revisão de design para a semana que vem."],
      ["Can you lay out the main steps?", "Você pode apresentar os passos principais?"],
      ["We need to scale up the design team.", "Precisamos expandir o time de design."],
      ["I ran into an issue with the prototype.", "Eu me deparei com um problema no protótipo."],
      ["She took note of all the feedback.", "Ela anotou todo o feedback."],
      ["Let's map out the user journey first.", "Vamos mapear a jornada do usuário primeiro."],
      ["I'll draw up a quick plan.", "Eu vou esboçar um plano rápido."],
      ["We need to push back on that deadline.", "Precisamos questionar aquele prazo."],
      ["Can you build on that idea?", "Você pode desenvolver essa ideia?"],
      ["I'll write up the meeting notes.", "Eu vou escrever as notas da reunião."],
      ["She cleaned up the Figma file before handoff.", "Ela organizou o arquivo Figma antes do handoff."],
      ["Let's check off the items on the list.", "Vamos marcar os itens da lista."],
      ["I had to start over after the client changed direction.", "Eu tive que começar do zero depois que o cliente mudou de direção."],
    ],
  },
];
